### ISSUE TITLE
你好，请问能增加冰箱控制功能吗？

### ISSUE THREAD

**Issue by xiamo23** [mac-zhou/midea-ac-py#100]
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
bash-5.1# midea-discover -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:msmart.scanner:Broadcast message sent: 0
DEBUG:msmart.scanner:Midea Local Data 10.10.1.22 837000b8200f00005a5a0111a8007a8                                                                                    0000000000000000000000000fafa0200008600000000000000000000000000006afa3617b2b9f7a                                                                                    9438d6a05954d556a2d3a34c23715f673014d07e9523e964909f7baa95492aa7540af99f2f02d639                                                                                    9348895155d7cd62c6bc8e5ea19dd773d6d799e28d556f65c5b022602d7fbdfe0d2e6091b990129b                                                                                    b411aa24d82f30c1e06c416020931f48926620dfe95e2311187491a2a49effb08da7ac6846a9de36                                                                                    c6630463d78bd0a2ba3bc9de3ba8f13b6
DEBUG:msmart.scanner:Decrypt Reply: 10.10.1.22 16010a0a2c19000030303030434144373                                                                                    130303130533044333139423031483134383532303030300d6d696465615f63615f3438353200000                                                                                    00002000000000000000000ca00000000000000847c9bd4bc5705830401202601030000000000000                                                                                    00000000000000000000000000000

**Comment by mac-zhou** [comment]
暂无计划
