### ISSUE TITLE
Support EU-OSK103

### ISSUE THREAD

**Issue by BigMiura** [mac-zhou/midea-ac-py#111]
**Describe the bug （描述一下问题）**
With midea-discover I can scan my AC but after that I see only errors, you can see it in the log.
With home assistant I have only empty entitys.

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**

> fabio@fabio-ubuntu:~$ midea-discover -d
> INFO:msmart.cli:Debug mode active
> INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
> INFO:msmart.cli:Sending Device Scan Broadcast...
> DEBUG:asyncio:Using selector: EpollSelector
> DEBUG:msmart.scanner:Broadcast message sent: 0
> DEBUG:msmart.scanner:Midea Local Data 192.168.1.77 837000c8200f00005a5a0111b8007a800000000004a8270b150b151463d40200001d0000000000000000018000000000436ee59185981acb80953897076f587787ebb386550d89a3c21abce6b500afc6ff9ba3eb53ca23c00d8f8eab3d45f8da1df38bcb21798b124621b72cc562e17b9da346cfc3769eff509ce3f73eca554306c867e13b66bf3c47ad04339bcf76ae4bdfb3e16e33d88768cc4c3d0658937d0bb19369bf0317b24d3a4de9e6a13106b8448ff8a89cfacf3682a621c04122189e7f9eb4015f4df1b13d3f0c26aa2bf6
> DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.77 4d01a8c02c19000030303030303050303030303030305131413834303744394536383031303030300b6e65745f61635f363830310000870002000000000000000000ac00acac00000000a8407d9e6801150029082115000302000000000000000000000000000000000000000000000000000000000000000000
> DEBUG:msmart.scanner:Midea Local Data 192.168.1.160 837000b8200f05425a5a0111a8007a8000000000000000000000000045e803000011000000000000000000000000000098c515ed3fea64df13e0c27b61e84fcb87ebb386550d89a3c21abce6b500afc6501b4983ef9cc3d51b7343512d1bc06850f3120e864eca588b828b69af80922be703a83ed4af68f9e390a73cf240c57c8bb9e6e39726e7af22ed2adc38c30dc6f31443d17c3aac03a7656614ae1dca44dd689654bd13f0d8066ea95ecf95bcc7db24e0db2789dc7fa79f21ab43182f2f
> DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.160 a001a8c02c19000030303030303050303030303030305131413834303744394544343334303030300b6e65745f61635f443433340000000001000000040000000000ac00000000000000a8407d9ed434069fcd0300080103030000000000000000000000000000000000000000
> DEBUG:msmart.scanner:Midea Local Data 192.168.1.228 837000b8200f05f05a5a0111a8007a800000000000000000000000003ded0200001d000000000000000000000000000071c689dfb128a5aa89f849a63ce651bf658e482a575f9f149308534ec98af6b04b54e339bd26465187e16d44f468f37cd10bd84e5ef2bcad2067702602c92dce3bca28212f56810da1e08db0898079f58bb9e6e39726e7af22ed2adc38c30dc6f31443d17c3aac03a7656614ae1dca443b3143974cb5ae4f0d2c7e19115082934f213ca11b4728a4f55266e617c4a1b3
> DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.228 e401a8c02c19000030303030303050303030303030305131413834303744394337383632303030300b6e65745f61635f373836320000000001000000040000000000ac00000000000000a8407d9c7862069fcd0300080103030000000000000000000000000000000000000000
> DEBUG:msmart.scanner:Midea Local Data 192.168.1.110 837000b8200f045d5a5a0111a8007a8000000000000000000000000098520300001d0000000000000000000000000000e8a2e2d38d7fd43fc24fdf7dd6020cd987ebb386550d89a3c21abce6b500afc63903ef171d34b30c8c8e56fb5c961dc58a6b8a236949fc24c775498c2712c9f4143466ca547091736cbb7faa6b439fa2a50bc4cd412f1ce53b276a62d7412834f31443d17c3aac03a7656614ae1dca44d52cb203821bc325826660244cca402980b7056e18ab1501297cc700fedf1abd
> DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.110 6e01a8c02c19000030303030303050303030303030305131413834303744394544343032303030300b6e65745f61635f443430320000000001000000040000000000ac00000000000000a8407d9ed402069fcd0300080103020000000000000000000000000000000000000000

> DEBUG:msmart.scanner:Socket timeout
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"a8341370-9bb4-4f64-8024-9f734d1b4392"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"39108674-f532-4336-9126-1420ec733e1f"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"a45a2baa-a190-4f48-831e-3b22d5c3832b"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"c1b92efc-c4bb-40b5-ac97-0030f1236dea"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"password error，please enter again.","errorCode":"3101"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"5f743393-3a19-4215-b9a8-431ba38adccd"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"88f11b81-9378-434b-97fe-7d5a8bc46c9d"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"a2376205-7ea5-447a-86e3-28dfcdf109d4"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"password error，please enter again.","errorCode":"3101"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"70672eee-6bf4-4e79-80f7-f0eb4df1e775"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"cc2b7fcd-a88a-4c82-a347-49714ed7478b"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"password error，please enter again.","errorCode":"3101"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"bc8b4697-0b9b-4412-9a5e-fbc6ec886826"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"midea_is_best@outlook.com","sessionId":"44c4ad60ee2d47518cb6339f937f424b20211121113948973","accessToken":"fe2658f1e2a821091586ad4af58efd8db920ebb829d567559397ded751813801","userId":"4826094","versionCode":"","leftCount":""},"errorCode":"0"}
> DEBUG:msmart.cloud:Retrying API call: 'user/login'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"bfa28fb9-ac3e-429e-b52a-d0618b6cdaa3"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"midea_is_best@outlook.com","sessionId":"44e2f5cefceb4e5cbe715a0d124f4d3d20211121113949709","accessToken":"5f35d4224d9d9acfc04825f32e8a1d08b920ebb829d567559397ded751813801","userId":"4826094","versionCode":"","leftCount":""},"errorCode":"0"}
> DEBUG:msmart.cloud:Retrying API call: 'user/login'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"d390668c-4d8e-4250-ae7e-95be94b04f2a"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"midea_is_best@outlook.com","sessionId":"21732a6a9f1840c1a540ea6b68343c0720211121113950384","accessToken":"1817202854b5460385dab2e4012ad92cb920ebb829d567559397ded751813801","userId":"4826094","versionCode":"","leftCount":""},"errorCode":"0"}
> DEBUG:msmart.cloud:Retrying API call: 'user/login'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"aeb165bf-34ab-4698-8e88-47a651afb474"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"midea_is_best@outlook.com","sessionId":"4b436469fa73481a939af1c68ae8e00a20211121113951030","accessToken":"5e3540de8325f52fce8a572a5d9799e0b920ebb829d567559397ded751813801","userId":"4826094","versionCode":"","leftCount":""},"errorCode":"0"}
> DEBUG:msmart.cloud:Retrying API call: 'user/login'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"0d61862c-c9a5-4885-8056-3763a18fc6ec"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"midea_is_best@outlook.com","sessionId":"fd87db61d9a1473cb7f451ef354a2da720211121113951670","accessToken":"99da0f069ab9fefbf74cb983e61e41cfb920ebb829d567559397ded751813801","userId":"4826094","versionCode":"","leftCount":""},"errorCode":"0"}
> DEBUG:msmart.cloud:Retrying API call: 'user/login'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
> DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
> ^CDEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
> DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"74e2262b-2ff8-4134-a23f-5249be29a592"},"errorCode":"0"}
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443

**Versions (版本信息)**
 - Home Assistant version: core-2021-11-4 Home Assistant OS
 - Midea msmart version: 0.1.35
 - Dongle WiFi: EU-OSK103

**Comment by BigMiura** [comment]
I don't if this is a bug or a feature request.
Thanks for your work.

p.s. I also wrote on Telegram, but I have not received a reply

**Comment by mac-zhou** [comment]
new version 0.1.36 fixed this issues，please try.
