### ISSUE TITLE
siri开启空调时，能够设置默认模式

### ISSUE THREAD

**Issue by langsking** [mac-zhou/midea-ac-py#113]
**Describe the solution you'd like （描述需求）**
发现每次siri开空调，都是制冷模式，能否提供默认模式的设置
**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题

**Comment by mac-zhou** [comment]
https://discussionschinese.apple.com/thread/252929546

非我这边的问题 我也有朋友遇到了 你直接说“将书房降到 26 度”等等
