### ISSUE TITLE
Retrieving token and k1 via adb logcat | grep doKeyAgree

### ISSUE THREAD

**Issue by valerachuk** [mac-zhou/midea-ac-py#116]
Hello,
Would you mind returning the manual on how to get token and k1 via "adb logcat | grep doKeyAgree", because it still works :)
Thankfully "Midea-Air-gettoken-only-oversea.apk" remained in my downloads folder.
https://github.com/mac-zhou/midea-ac-py/commit/bef3e3665eb67e09d75480b34b1684ab59826551#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L52-L69

**Comment by mac-zhou** [comment]
The operation is too complicated `midea-discover` can be very simple
