### ISSUE TITLE
HACS下载后在集成那里搜索不出来

### ISSUE THREAD

**Issue by ldwddv11** [mac-zhou/midea-ac-py#122]
**Describe the bug （描述一下问题）**
custom_components文件夹里面已经生成midea_ac，里面有三个文件，但是依然无法在集成搜索出来，请问怎么解决？

**Comment by kingtao1024** [comment]
你需要在配置文件中手动配置，无法通过UI添加此集成

**Comment by ldwddv11** [comment]
不好意思我不太熟悉，手动配置是怎么操作的？





------------------ 原始邮件 ------------------
发件人: kingtao1024 ***@***.***&gt;
发送时间: 2022年2月16日 16:41
收件人: mac-zhou/midea-ac-py ***@***.***&gt;
抄送: ldwddv11 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [mac-zhou/midea-ac-py] HACS下载后在集成那里搜索不出来 (Issue #122)





 
你需要在配置文件中手动配置，无法通过UI添加此集成
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kingtao1024** [comment]
HA配置文件目录下的configuration.yaml里面，增加
climate:
  - platform: midea_ac
    host: 192.168.1.100
    id: 123456789012345
    # v3 need token and k1(key)
    # token: ACEDDA53831AE5DC...(Length 128)
    # k1: CFFA10FC...(Length 64)
