### ISSUE TITLE
Midea v3 key and Token

### ISSUE THREAD

**Issue by jesterino** [mac-zhou/midea-ac-py#126]
**Describe the bug （描述一下问题）**

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题

**Versions (版本信息)**
 - Home Assistant version: 2022.2.6
 - Midea msmart version: 3

I own 4 Midea AC, (3 version 2 and 1 Version 3)
I put the key and token of version 3 in yaml file but i see that token and key of version 3 change any time i run midea-discover

INFO:msmart.cli:*** Found a device: {'type': 'ac', 'support': True, 'version': 3, 'ip': '192.X.X.X', 'id': 31885837349024, 'port': 6444, 'token': 'CEFE0507FC334D9738A3BC13FBB29D0253B8EAB3B9DC8FC6E03FF9B9D0DB3BCCBA08ABE8EB0475CA3CA1226C7A4339B86EA6DD85C504F3B552E53ACEBF2DF2B3', 'key': '8FB4624EDCDF437EBAC8CB5421D9C136046712F18B71469EA69AD9EF2D8BBA4E', 'ssid': 'net_ac_AC8E'} 
Is possible to setup this model ?
Thank you

**Comment by mac-zhou** [comment]
token and k1 can be reuse, just run `midea-discover` once
