### ISSUE TITLE
Siri控制空调提示：“好的，设成什么值”

### ISSUE THREAD

**Issue by ComLin010** [mac-zhou/midea-ac-py#137]
**Describe the bug （描述一下问题）**
大佬最近升级HA系统后在homekit里出现了风速控制，但基本操作后无反应
后发现Siri无法控制空调，不管是询问空调的状态还是控制温度，控制开关
SIri都会说“好的，设成什么值”

有没有大佬遇到过这种情况，要怎么解决

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题

**Versions (版本信息)**
 - Home Assistant version: Home Assistant OS 7.4
 - Midea msmart version: f5a2646

**Comment by mac-zhou** [comment]
我不知道
