### ISSUE TITLE
HELP needed: pip3 install msmart midea-discover

### ISSUE THREAD

**Issue by Asom-Velz** [mac-zhou/midea-ac-py#140]
Hi 

I am running Home Assistant in VMware Workstation and the only think that I have in the machine console is the ha>

Were I have to run the
  pip3 install msmart
  midea-discover

Regards

**Comment by ObiWanCanOweMe** [comment]
I ran that on another machine (M1 Mac Mini) where I have gcc and python installed. AFAIK these commands do not have to be run from your HA installation so long as the Midea device and machine can see each other or are on the same network. There's no supported method of installing gcc on HA

**Comment by mill1000** [comment]
You are correct. It is not necessary to run `midea-discover` on the machine running HA. It is only used to fetch the IP, ID, Token and K1.

Could you close this issue?
