### ISSUE TITLE
Cant seem to find my AC unit with midea-discover

### ISSUE THREAD

**Issue by jaygrovr** [mac-zhou/midea-ac-py#142]
I have installed the midea python on my windows machine and when i try to use midea-discover, it sits there with one reply line of 
"INFO:msmart.cli:msmart version: 0.2.2 Currently only supports ac devices."

I am trying to find my pioneer mini split on my network and I have a nethome account but I dont have a midea account.  
When running the command I am using my username and password for my nethome account which is pioneers app to control the AC unit.

**Versions (版本信息)**
 - Home Assistant version: 
 - Midea msmart version: 0.2.2

**Comment by jaygrovr** [comment]
more info on log when I had to kill the process
Exception ignored in: <module 'threading' from 'c:\\users\\jason\\appdata\\local\\programs\\python\\python39\\lib\\threading.py'>
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python39\lib\threading.py", line 1411, in _shutdown
    atexit_call()
  File "c:\users\jason\appdata\local\programs\python\python39\lib\concurrent\futures\thread.py", line 31, in _python_exit
    t.join()
  File "c:\users\jason\appdata\local\programs\python\python39\lib\threading.py", line 1029, in join
    self._wait_for_tstate_lock()
  File "c:\users\jason\appdata\local\programs\python\python39\lib\threading.py", line 1045, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt:
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<scandevice.support_test() running at c:\users\jason\appdata\local\programs\python\python39\lib\site-packages\msmart\scanner.py:44> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at c:\users\jason\appdata\local\programs\python\python39\lib\asyncio\futures.py:384, <TaskWakeupMethWrapper object at 0x000002DA1D1F8E80>()]>>

**Comment by jaygrovr** [comment]
here is more of the debug log when i add my username and password for the midea account

DEBUG:msmart.cloud:Retrying API call: 'user/login'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"69b162d2-5ebf-4320-8cc4-eddeea4a5a4d"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"jaygrovr@yahoo.com","sessionId":"8053b5784f1f46b48b8191006095d52b20220416175324584","accessToken":"bb96d758cf49d2a1c1f4f7381a9928a2b920ebb829d567559397ded751813801","userId":"5803384","versionCode":"","leftCount":""},"errorCode":"0"}
DEBUG:msmart.cloud:Retrying API call: 'user/login'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"b07bb4c2-674d-4134-bdf4-b4c83ae6d144"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"jaygrovr@yahoo.com","sessionId":"cb419f2d1457428f8194cfa5032bf5ac20220416175325610","accessToken":"a81ee97684fdc0d81484a4dc1aa9b089b920ebb829d567559397ded751813801","userId":"5803384","versionCode":"","leftCount":""},"errorCode":"0"}
DEBUG:msmart.cloud:Retrying API call: 'user/login'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"f4096671-5aff-46fd-8ee6-6a859a06e7e1"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"jaygrovr@yahoo.com","sessionId":"90e843d4e6b446989916325deccc1de520220416175327546","accessToken":"5d47bcd32bf7028602c5ba19ff3d620cb920ebb829d567559397ded751813801","userId":"5803384","versionCode":"","leftCount":""},"errorCode":"0"}
DEBUG:msmart.cloud:Retrying API call: 'user/login'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"df3d67f3-1093-469c-bc55-34971d8efb1e"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"jaygrovr@yahoo.com","sessionId":"b8419a83df074e36b3d49fbb9a8da86520220416175329351","accessToken":"cdf1a6fb559c9e138163184e7f59f4c0b920ebb829d567559397ded751813801","userId":"5803384","versionCode":"","leftCount":""},"errorCode":"0"}
DEBUG:msmart.cloud:Retrying API call: 'user/login'

**Comment by mac-zhou** [comment]
#141

**Comment by mac-zhou** [comment]
#141
