### ISSUE TITLE
a lot of errors, hope someone can help me out?!

### ISSUE THREAD

**Issue by Barry40** [mac-zhou/midea-ac-py#143]
Hi all,

i'm getting a lot of errors when using midea-discover, hope someone can help me out of what i'm doing wrong..
`  244  midea-discover -d
  245  DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/iot/secure/getToken HTTP/1.1" 200 None
  246  DEBUG:msmart.cloud:Response: {"msg":"system error","errorCode":"9999"}
  247  DEBUG:msmart.cloud:Restarting session: '9999' - 'system error'
  248  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
  249  DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/iot/secure/getToken HTTP/1.1" 200 None
  250  DEBUG:msmart.cloud:Response: {"msg":"system error","errorCode":"9999"}
  251  DEBUG:msmart.cloud:Restarting session: '9999' - 'system error'
  252  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
  253  DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
  254  DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
  255  DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
  256  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
  257  DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
  258  DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
  259  DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
  260  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
  261  DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
  262  DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"038b99f5-5195-4379-9031-d652ac97602d"},"errorCode":"0"}
  263  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
  264  DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
  265  DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"1978c75b-417d-49ef-b1f8-4f161bb8094d"},"errorCode":"0"}
  266  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
  267  DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
  268  DEBUG:msmart.cloud:Response: {"msg":"password error，please enter again.","errorCode":"3101"}
  269  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
  270  DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
  271  DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
  272  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
  273  DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None`
  thank you

**Comment by mac-zhou** [comment]
#141

**Comment by mac-zhou** [comment]
#

**Comment by Barry40** [comment]
Update 0.2.3 fixed to get token. 
Everything works again!
