### ISSUE TITLE
Show entities only

### ISSUE THREAD

**Issue by EvertJob** [mac-zhou/midea-ac-py#153]
**Describe the bug （描述一下问题）**
Plugin shows only a entity and does not show up as a device. Therefor I cannot do much with the automations of it

**Versions (版本信息)**
 - Home Assistant version: Home Assistant Core 2022.5.2
 - Midea msmart version: 0.0.23

**Comment by edwmurph** [comment]
i think you can still create automations with only entities

i.e. in this case in the automation, call the service "Climate set temperature" and specify the corresponding entity
