### ISSUE TITLE
"ClimateDevice is deprecated, modify MideaClimateACDevice to extend ClimateEntity"

### ISSUE THREAD

**Issue by Asom-Velz** [mac-zhou/midea-ac-py#18]
HI 

I receive the following warning after the latest update to 4.9

"ClimateDevice is deprecated, modify MideaClimateACDevice to extend ClimateEntity"

As I have read : There has been a change with naming the entities. For now they’re just a warning for the code owners to do some work. But after a certain update it will break.
All integrations in Home Assistant have been upgraded. Custom component authors need to do the migration themselves. You can do this while keeping backwards compatibility by using the following snippet:

https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/?fbclid=IwAR31aU6j2Z5zyX0DhwArOXHnI9YWMkcueVM7rRCHS1FfhFcLG4uitA528yM

This is my configuration.yaml - which was working fine before the update

climate:
# Configuration for MideaA/C
-  platform: midea_ac
   host: !secret ac_ip
   id: !secret ac_id

**Describe the bug （描述一下问题）**

**Versions (版本信息)**
 - Home Assistant version: 0.110.5
 - Midea msmart version: 

![midea](https://user-images.githubusercontent.com/65943619/83950734-a39e1200-a835-11ea-844b-be5a5eafb7f8.jpg)

**Comment by Dinges28** [comment]
**Versions (版本信息)**

- Home Assistant version: 0.111.4


** error **
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:555
Integration: Klimaat (documentation, issues)
First occurred: 11:58:45 (1 occurrences)
Last logged: 11:58:45

ClimateDevice is deprecated, modify MideaClimateACDevice to extend ClimateEntity

**Comment by mac-zhou** [comment]
thanks. Updated
