### ISSUE TITLE
outfoor temperature displays in Celsius, even when unit is set to Fahrenheit

### ISSUE THREAD

**Issue by jtronicus** [mac-zhou/midea-ac-py#191]
**Describe the bug （描述一下问题）**
outdoor_temperature attribute displays in Celsius, even when unit is set to Fahrenheit.   The attributes below from Home Assistant show an indoor temperature of 73F and an outdoor temperature of 32C (which is about 90F)

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
```
hvac_modes: auto, cool, dry, heat, fan_only, off
min_temp: 63
max_temp: 86
target_temp_step: 1
fan_modes: Auto, Full, High, Medium, Low, Silent
preset_modes: none, eco, boost
swing_modes: Off, Vertical, Horizontal, Both
current_temperature: 73
temperature: 68
fan_mode: Auto
preset_mode: none
swing_mode: Off
outdoor_temperature: 32
friendly_name: midea_ac_xxxxxxxxxxx
supported_features: 57
```

**Versions (版本信息)**
 - Home Assistant version: 2022.8.1

**Comment by mill1000** [comment]
What version of the integration are you using?

**Comment by jtronicus** [comment]
I am using version 0.2.3, downloaded from HACS store

**Comment by mill1000** [comment]
I believe this issue has been fixed in master, it just hasn't been released yet.

**Comment by jtronicus** [comment]
I tried installing master, but it appears to have some dependency issues.  I will just wait for the next release.

Thanks!
