### ISSUE TITLE
Support Mute Function

### ISSUE THREAD

**Issue by amoyzc** [mac-zhou/midea-ac-py#194]
Currently, all operations will cause the AC to beep, it could be pretty annoying.
Are we able to support mute function so we can control the ac without beeping?

The function is supported by the remote control after press the 'led' button on it.

**Comment by mill1000** [comment]
~The underlying library supports this function. Just need to expose it to HA.
https://github.com/mac-zhou/midea-msmart/blob/97723d055d8e5a3775eaaca96807f2dbbd6db2aa/msmart/device/AC/appliance.py#L224-L232~

This is already supported. In your configuration set `prompt_tone` to false.

**Comment by amoyzc** [comment]
> ~The underlying library supports this function. Just need to expose it to HA. https://github.com/mac-zhou/midea-msmart/blob/97723d055d8e5a3775eaaca96807f2dbbd6db2aa/msmart/device/AC/appliance.py#L224-L232~
> 
> This is already supported. In your configuration set `prompt_tone` to false.

Ohhhh... Thanks!
