### ISSUE TITLE
Rotenso AC msmart.device.AC.appliance

### ISSUE THREAD

**Issue by NoMoRe023** [mac-zhou/midea-ac-py#207]
So I have setup everything right (at least I think so): device IP and device ID  (from QR code), I do can see my AC in dashboard, but controling AC doesn't do anything. Here is what I have in logs:

_Logger: msmart.device.AC.appliance
Source: /usr/local/lib/python3.10/site-packages/msmart/device/AC/appliance.py:114
First occurred: 19:55:12 (12 occurrences)
Last logged: 20:14:22

Got Null from 192.168.88.229:6444 Version: 2 Count: 0 Spend time: 6.01
Got Null from 192.168.88.229:6444 Version: 2 Count: 0 Spend time: 2.0
Got Null from 192.168.88.229:6444 Version: 2 Count: 0 Spend time: 3.01
Got Null from 192.168.88.229:6444 Version: 2 Count: 0 Spend time: 5.01
Got Null from 192.168.88.229:6444 Version: 2 Count: 0 Spend time: 3.07_

 - Home Assistant version: 2023.1.2
 - Midea msmart version: 0.1.27

Apologies if I posted anything wrong. Just getting started with HA and github.

EDIT: Already added fan_only_workaroud: true in configuration

**Comment by mill1000** [comment]
What was the output of `midea-discover`?
