### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by Borty97** [mac-zhou/midea-ac-py#219]
After installing `midea-discover` and using `midea-discover -a YOUR_ACCOUNT -p YOUR_PASSWORD` to login and get the climate ID it shows this error:
![image](https://github.com/mac-zhou/midea-ac-py/assets/60492018/48f43973-a9e2-4161-b18a-4fe99e09319e)
There is no way to get information, even setting `-i HOST_IP`

**Versions (版本信息)**

- Home Assistant version:

<html>
<body>

Versió | core-2023.8.1
-- | --
Tipus d'instal·lació | Home Assistant Container
Desenvolupador | false
Supervisor | false
Docker | true
Usuari | root
Entorn virtual | false
Versió de Python | 3.11.4
Família del sistema operatiu | Linux
Versió del sistema operatiu | 4.4.302+
Arquitectura de la CPU | aarch64
Zona horària | Europe/Madrid
Directori de configuració | /config

</body>
</html>

- Midea msmart version:  `v0.2.3`

**Comment by mill1000** [comment]
What is the output when running with the `-d` option? e.g. `midea-discover -d` or `midea-discover -d -i HOST_IP`

What brand & model of devices do you have? Better yet, can you confirm the model of the WiFi dongle?

**Comment by Borty97** [comment]
`DEBUG: asyncio: Using selector: EpollSelector`
`DEBUG: msmart.scanner: Broadcast message sent: 1`
`DEBUG: msmart.scanner: Socket timeout`

In both scripts.

I use the Carrier WiFi Kit: https://gruporp.es/3333-kit-wifi-carrier-aire-acondicionado-split-pared-serie-gold.html

**Comment by mill1000** [comment]
Has the device been added to the network via the manufacturer's app (MSmartHome, NetHome Plus, etc)?

What is the network configuration of your docker container (e.g. host, bridged, etc)? Are HA and the device on the same subnet?

Would you be comfortable running Wireshark to check the network traffic? That would let us determine if the broadcast isn't going out, or if we're failing to receive the response.

**Comment by Borty97** [comment]
**Has the device been added to the network via the manufacturer's app (MSmartHome, NetHome Plus, etc)?**
Yes, first with NetHome Plus and after with MSmartHome (when I realised it didn't work).
**What is the network configuration of your docker container (e.g. host, bridged, etc)? Are HA and the device on the same subnet?**
Host. Maybe they are in differents subnets (HA is connected via LAN) and the A/C via the IoT Wi-Fi that my router has (https://www.tp-link.com/es/home-networking/wifi-router/archer-c6/).

**Would you be comfortable running Wireshark to check the network traffic? That would let us determine if the broadcast isn't going out, or if we're failing to receive the response.**
I will look about this software. I never used it before

**Comment by mill1000** [comment]
> Host. Maybe they are in differents subnets (HA is connected via LAN) and the A/C via the IoT Wi-Fi that my router has (https://www.tp-link.com/es/home-networking/wifi-router/archer-c6/).

Host is good. Ah that's interesting. Perhaps it is isolating the device from your main network. I found this in some release notes for the C6.
![image](https://github.com/mac-zhou/midea-ac-py/assets/6924622/a504c5e8-4c26-4d27-8d2a-d4457b18ec4e)

Can you ping the IP from the HA system?

**Comment by Borty97** [comment]
I had my SynologyNAS isolated... Thanks

Anyway, now I have this error:
![image](https://github.com/mac-zhou/midea-ac-py/assets/60492018/dd6eca35-c416-4195-9dd9-1a60bc786ac3)

**Comment by Borty97** [comment]
Finally I used the https://github.com/georgezhao2010/midea_ac_lan Midea AC LAN integration. It works perfect

**Comment by mill1000** [comment]
Cool. That extension is a good option, I also have a fork with the above bug fixed and other improvements.

https://github.com/mill1000/midea-ac-py
https://github.com/mill1000/midea-msmart
