### ISSUE TITLE
Lovelace integration

### ISSUE THREAD

**Issue by bit111** [mac-zhou/midea-ac-py#26]
Hello,
is there a Lovelace (home-assistant) integration?
The "example configuration" you wrote in project home page is in yaml.
Thanks.

**Edit:**
Ok, 
I just used thermostat component. It appears on my dashboard but it doesn't works.
I am unable to turn on/off it via home-assistant.
Name | Version
------------ | -------------
Home Assistant (core) | 0.110.1
HACS store | 1.1.1

There is no log in Home-Assistant.

**Comment by bit111** [comment]
Ok, 
I just used thermostat component. It appears on my dashboard but it doesn't works.
I am unable to turn on/off it via home-assistant.
Hacs version: 1.1.1
Home Assistant (core) version: 0.110.1

**Comment by mac-zhou** [comment]
```pip3 install msmart
midea-discover```
Confirm if your device is supported

**Comment by bit111** [comment]
It seems not to be supported:
```
INFO:msmart.lan:Couldn't connect with Device 192.168.x.x:6444
INFO:msmart.cli:*** Found a unsupported '0xac' at 192.168.x.x - id: 18691********** - sn: P0000000*************** - ssid: net_ac_****
```
My AC has another brand but it use the same **OSK102 wifi usb**. Can you tell me how can I make your code compatible?

**Comment by mac-zhou** [comment]
wow. This is the first I've heard of this wifi usb.
In my area, it's integrated.
Sorry, it's not supported.

**Comment by bit111** [comment]
Ok,
I read in a forum your comment in which you said that there was a problem with the new algorithms of this AC. Could that be?
Can you tell me how can I migrate your code to make it work with my ac?
Thanks

**Comment by jmadejek** [comment]
I have Midea (3xRotenso Imoto) with USB dongle.  They works with Midea Air and NetHome Plus apps. I discovered that there are two versions of WiFi dongle. OSK102 and OSK103. Both works with HA and cloud integration (https://github.com/andersonshatch/midea-ac-py) but just OSK102 works with your local integration.

My only one OSK102 starts with id: 18691... and both OSK103 start with id: 23089...

**Comment by mac-zhou** [comment]
yes. OSK103 run with a new protocol, you can try: https://github.com/kueblc/midea-msmart/tree/support-8370

**Comment by jmadejek** [comment]
> yes. OSK103 run with a new protocol, you can try: https://github.com/kueblc/midea-msmart/tree/support-8370

Can you explain me how to use it in Home assistant? Should I place/replace it in some directory?

**Comment by jmadejek** [comment]
> > yes. OSK103 run with a new protocol, you can try: https://github.com/kueblc/midea-msmart/tree/support-8370
> 
> Can you explain me how to use it in Home assistant? Should I place/replace it in some directory?

I'm using HassOS 4.11 and cant use pip3, have to put it somewhere. I tested it on my RPi with Raspbian but dont have lib/python direcory in hassio

**Comment by mac-zhou** [comment]
Currently in beta, you can waiting

**Comment by jmadejek** [comment]
> Currently in beta, you can waiting

Aby important differences for enduser between OSK102 and OSK103? With one is better/more stable? Because I can still replace them.

**Comment by mac-zhou** [comment]
I think there is no difference in function.
The difference is the encryption protocol.
OSK103 use a new protocol, there is no stable decryption method now.
so, I recommend OSK102.

**Comment by mac-zhou** [comment]
and you can join telegram group https://t.me/joinchat/BhU6LRytPXLsiqTIar0jqg

**Comment by deuntje** [comment]
I also have an OSK103 dongle in my AC and would like to get local control instead of the cloud connection. Do I understand it correctly that you're working on integrating the new protocol which the OSK103 is using?

**Comment by mac-zhou** [comment]
> I also have an OSK103 dongle in my AC and would like to get local control instead of the cloud connection. Do I understand it correctly that you're working on integrating the new protocol which the OSK103 is using?

no.
Another developer is following up.
https://github.com/WMP/midea-ac-py/tree/support-8370
https://github.com/WMP/midea-ac-py/wiki/AC-module-compatibility
