### ISSUE TITLE
EVA II PRO WiFi Smart Dehumidifier support?

### ISSUE THREAD

**Issue by pax2011** [mac-zhou/midea-ac-py#27]
Does this custom component support EVA II PRO WiFi Smart Dehumidifier? 
like this https://github.com/barban-dev/midea_inventor_dehumidifier ?

**Comment by drageloth** [comment]
Try [this](https://github.com/drageloth/midea_inventor_dehumidifier) and see if it works for you. It may throw a lot of errors in the log, but if it works....
