### ISSUE TITLE
Getting the current firmware version

### ISSUE THREAD

**Issue by ttimpe** [mac-zhou/midea-ac-py#29]
I am working on a homebridge plugin for Midea AC units and I‘m trying to get the firmware version currently running on the device.

Does anyone know if the firmware version is embedded somewhere in the appliance response?

I already found a call to the cloud API (https://mapp.appsmb.com/v1/app2base/data/transmit?serviceUrl=/ota/version) in the app, however my call (using the applianceId and the userId as parameters) is failing with ValueInvalid error. Is anyone interested in this, familiar with the API and wanting to help?

Thank you

Tobias Timpe

**Comment by mac-zhou** [comment]
Sorry, I'm not interested in the API.
