### ISSUE TITLE
Add more HVAC models

### ISSUE THREAD

**Issue by hillaliy** [mac-zhou/midea-ac-py#32]
Hi I love your work it's great.
Do you think that it possible to add more HVAC?
I have Electra HVAC that work also with a cloud like Midea.
I will send you anything you need.
Please!!!

**Comment by floringhimie** [comment]
Also Starlight AC work with Midea cloud, on midea-discover I get 0xac but unsupported. In HA AC is unavailable.

**Comment by mac-zhou** [comment]
try new version
