### ISSUE TITLE
Found a unsupported device 

### ISSUE THREAD

**Issue by gaochunmeng** [mac-zhou/midea-ac-py#36]
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.23
INFO:msmart.cli:Sending Device Scan Broadcast...
INFO:msmart.cli:Midea Local Data 192.168.142.170 837000c8200f00005a5a0111b8007a80000000001c2634150b0a1414c822150000930000000000000000018000000000267183c24ba5db6e5b4cce63e715a068cd12cdf578f53a39abc64ce617c6acb82c34bebef0fdd12c9c7c1752d2bfb60279d61bc6ed3ce6429046a4768cb9f8c99b6d9d3c5bddedd5b43bdcfbaec9648bc083b3c640ad7ba255dddf95919675ad4bdfb3e16e33d88768cc4c3d0658937d96fbcce99f70c976413c2f05f60f82e72c2909bfcae62da1ed3f52058c69d195398d6a97a75806510fd5bb9844ea8c77
INFO:msmart.cli:Decrypt Reply: 192.168.142.170 aa8ea8c02c19000030303030303033313132323031323336393039303530353232353830303030300d6d696465615f61635f323538300000830002000000000000000000ac00acac00000000a0681c048a10150015032018000300000000000000000000000000000000000000000000000000000000000000000000
DEBUG:msmart.command:Finalize request data: aa20ac00000000000003418100ff03ff0002000000000000000000000000192e25
DEBUG:msmart.lan:Sending to 192.168.142.170:6444 5a5a01116800200000000000171934150b0a1414c8221500009300000000000000000000000000006b000a76e27eed2c3647e57d8602df8b9981402b1d7f5153d47b03e0e31cd254b1c2205f69843a3c2f9a56fd694277b4651b5c49fbcfc27bd1e6a04e31430c21

INFO:msmart.lan:Couldn't connect with Device 192.168.142.170:6444
DEBUG:msmart.device:refresh - Recieved from 192.168.142.170, c82215000093:
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.142.170 - port: 6444 - id: 161628210668232 - sn: 00000031122012369090505225800000 - ssid: midea_ac_2580
INFO:msmart.cli:Midea Local Data 192.168.142.118 837000c8200f00005a5a0111b8007a8000000000f12634150b0a1414ec221500009300000000000000000180000000001919f0ed0673eee9b4e22f6278439436cd12cdf578f53a39abc64ce617c6acb8d854f3442ed531b1e8a5d5a9a914cc9a8f29037b123de3281cbcfa2365dc75969c45e590fa306ad3c3b6f18ee366bcdd595df4a2a58a7d227078a0864466f8504bdfb3e16e33d88768cc4c3d0658937d96fbcce99f70c976413c2f05f60f82e7c59646189b83d711643ff63b5dd453d689271b4f93c0725cbb46a625f0cde58f
INFO:msmart.cli:Decrypt Reply: 192.168.142.118 768ea8c02c19000030303030303033313132323031323336393039303530353232353832303030300d6d696465615f61635f323538320000830002000000000000000000ac00acac0000000030b237a738a9150015032018000300000000000000000000000000000000000000000000000000000000000000000000
DEBUG:msmart.command:Finalize request data: aa20ac00000000000003418100ff03ff00020000000000000000000000002152f9
DEBUG:msmart.lan:Sending to 192.168.142.118:6444 5a5a01116800200000000000182134150b0a1414ec221500009300000000000000000000000000006b000a76e27eed2c3647e57d8602df8bc24133a0909225f1481c3b73abacf8ec0bdaf60a4e381fb221a9a82463236a1bc1379d9cf6965ccc1fecb72767975c09

INFO:msmart.lan:Couldn't connect with Device 192.168.142.118:6444
DEBUG:msmart.device:refresh - Recieved from 192.168.142.118, ec2215000093:
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.142.118 - port: 6444 - id: 161628210668268 - sn: 00000031122012369090505225820000 - ssid: midea_ac_2582

**Comment by mac-zhou** [comment]
you can try this repo https://github.com/WMP/midea-ac-py/tree/support-8370#install-fake-cloud-only-if-you-have-protocol-version-3 or you want to drop the Midea USB DONGLE  with  ESPHome.
