### ISSUE TITLE
 integration problems with integrated wifi air conditioner

### ISSUE THREAD

**Issue by gladiangel** [mac-zhou/midea-ac-py#39]
I have a midea air conditioner with integrated wifi .... I followed all the parameters indicated by the repositories but nothing .... there is the extent of the air conditioner but nothing works ....

**Comment by GrSoul** [comment]
Same problem. The integration has been added successfully but I cannot control the AC.

**Comment by gryzli133** [comment]
do you guys see the device somewhere? I have two AC's with OSK102 modem, so should work. I set statis IP, got the device ID. Set everything in HA, but don't see any new AC device in my dashboard...

**Comment by rokam** [comment]
Is this still an issue?

**Comment by gryzli133** [comment]
My both devices are working now fine. It looks like one or other restart helped in my case.

**Comment by mac-zhou** [comment]
If you still have problems, please reopen this issue
