### ISSUE TITLE
希望能适配华菱空调的支持。。

### ISSUE THREAD

**Issue by boyyao** [mac-zhou/midea-ac-py#4]
抓了华菱空调的关机包。希望能适配。。感激涕零

[华菱空调关机.zip](https://github.com/mac-zhou/midea-ac-py/files/4627570/default.zip)

**Comment by boyyao** [comment]
[华菱开加减关.zip](https://github.com/mac-zhou/midea-ac-py/files/4627678/default.zip)
重新抓了一次。开机-加温度-减温度-关机

**Comment by mac-zhou** [comment]
看了抓包 暂不支持

**Comment by andr2000** [comment]
This protocol is also used for my Midea Mission II AC and this is why the current implementation cannot handle it.
[no_discovery_6444.zip](https://github.com/mac-zhou/midea-ac-py/files/4654862/no_discovery_6444.zip)

**Comment by mac-zhou** [comment]
> This protocol is also used for my Midea Mission II AC and this is why the current implementation cannot handle it.
> [no_discovery_6444.zip](https://github.com/mac-zhou/midea-ac-py/files/4654862/no_discovery_6444.zip)

sorry Not currently supported

**Comment by mac-zhou** [comment]
升级msmart到0.1.15试试，我暂时没在这里升级
直接改custom_components/midea_ac/manifest.json

**Comment by mac-zhou** [comment]
美的新的协议，暂时无法支持

**Comment by w4mxl** [comment]
请问现在支持华凌了吗？

**Comment by xiaolei0125** [comment]
华凌空调， [msmart.lan] Couldn't connect with Device 192.168.1.128:6444,   直接telnet测试6444端口是开的；

**Comment by mac-zhou** [comment]
华凌空调 只要是使用类似协议是支持的 
如果有问题 请给出相关日志

**Comment by rheatin** [comment]
> 华凌空调 只要是使用类似协议是支持的 如果有问题 请给出相关日志

宝，刚试了下，成功了！可能上次我哪里配置有问题，谢谢你😊
