### ISSUE TITLE
Found a unsupported device

### ISSUE THREAD

**Issue by oleewear** [mac-zhou/midea-ac-py#42]
Hi I cannot connect my AC to HA, it's always showing up as:
midea_ac_XXXX00000015 (XXXX are numbers) became unavailable

INFO:msmart.lan:Couldn't connect with Device 192.168.1.34:6444
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.1.34 - port: 6444 - id: 2XXXXX44212500 - sn: 000000P0000000QXXXXX71792A50000 - ssid: net_ac_XXXX

**Versions (版本信息)**
 - Home Assistant version: 1.18
 - Midea msmart version:  0.1.24

Thanks and Regards
Oliver

**Comment by twocolors** [comment]
INFO:msmart.lan:Couldn't connect with Device 192.168.0.31:6444
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.0.31 - port: 6444 - id: 2xxxxxx0943592 - sn: 000000P0000000QxxxxxxxxA01390000 - ssid: net_ac_0139

**Comment by mac-zhou** [comment]
you can try this repo https://github.com/WMP/midea-ac-py/tree/support-8370#install-fake-cloud-only-if-you-have-protocol-version-3 or you want to drop the Midea USB DONGLE  with  ESPHome.
