### ISSUE TITLE
HomeKit端能否加入除湿和扫风功能？另外能否加入蜂鸣声

### ISSUE THREAD

**Issue by briantang1117** [mac-zhou/midea-ac-py#45]
HomeKit端能否加入除湿和扫风功能？另外能否加入蜂鸣声

**Comment by mac-zhou** [comment]
HomeKit不是我控制的
最近的下个版本会加入蜂鸣声

**Comment by 1043717432** [comment]
ha里接入的空调，想在hk环境中带有风速调节功能，请问您知道是更改HA里的哪个文件呢

**Comment by briantang1117** [comment]
查了一下home assistant的hk组件是ha自己维护的 没办法

————————
唐 丰圆 Brian
College of Communication and Art Design
University of Shanghai for Science and Technology
***@***.***

**Comment by 1043717432** [comment]
> 查了一下home Assistant的hk组件是ha自己维护的没办法———————— 唐丰圆布赖恩上海科技大学传播与艺术设计学院***@***.** *
> […](#)
> 在 2021 年 7 月 15 日，09:54，1043717432 ***@***.***> 留言： 哈里接入的空调，想在香港环境中带有风速调节功能，请您知道是更改 HA 里的哪个文件呢 — 您收到此消息是因为您创作了该线程。直接回复此邮件，在 GitHub 上查看，或取消订阅。

我是不知道在docker里映射哪个路径出来，其实就是麻烦每次升级ha都必须替换一次文件而已。
