### ISSUE TITLE
fan_mode high not 100%

### ISSUE THREAD

**Issue by bernux** [mac-zhou/midea-ac-py#49]
**Describe the bug**
When setting fan_mode to high, the fan is only at 80%
When setting to 100% with the remote or the app it appears like Auto in HA
When setting to auto in HA it's really auto 

**Versions**
 - Home Assistant version: 2020.12.1
 - Midea msmart version: 0.1.24

**Comment by mac-zhou** [comment]
try new version

**Comment by mac-zhou** [comment]
If you still have problems, please reopen this issue
