### ISSUE TITLE
WIFI Modules OSK102 / OSK103

### ISSUE THREAD

**Issue by Asom-Velz** [mac-zhou/midea-ac-py#50]
**Describe the bug （描述一下问题）**
Hi

I am using an A/C with WiFi Module OSK102 for more than a year and it was working "Ok" (when it is available...)
We have bought a new A/C same model but the with WiFi Module is OSK103 I found the device id but although it creates a new entity the device show unavailable in Home assistant - in the Midea app is available and working ok - both  A/Cs

"Old A/C" midea_ac_81xxx00000xx -> off ->(OSK102 id: 17xx21xx09xx0x)
"New A/C" midea_ac_d3xxx00000xx -> Unavailable ->(OSK103 id: 31xx58xx26xx8x)

If I switch the Wifi modules and put the OSK103 in the "old A/C" and the OSK102 to the "new A/C" I have exactly the opposite
the new A/C is recognized and the old A/C is unavailable 

**Versions (版本信息)**
 - Home Assistant version: 
 - core-2021.1.5 
 - supervisor-2021.01.7
 - 
 - Midea msmart version: c1bd84c

**Comment by christosmilts** [comment]
I have exactly the same issue -> One 'old' OSK working & one 'new' OSK not working. Would love to find a solution for that!

**Comment by apovadash** [comment]
Hi,

I have bought a new unit with EU-OSK103 and not available too

**Comment by Asom-Velz** [comment]
OSK103 modules are more stable with the midea app and A/C is always online but.... it is not recognized in Home Assistant with midea-ac-py 😕😕😕

**Comment by GyniO** [comment]
+1
I too have OSK103, I have added to HA but cannot control device.

If want help, test, information or something else just let me know.
A/C Rotenso Versu  - app NetHome plus
https://rotenso.pl/produkt/versu-silver/

**Comment by dartek66** [comment]
me also does not work with module 103, please help.

**Comment by msanchezt** [comment]
https://github.com/WMP/midea-ac-py/tree/support-8370#install-fake-cloud-only-if-you-have-protocol-version-3

**Comment by Asom-Velz** [comment]
Hi!!
Does someone with OSK-103 module managed to solve the problem? 
Since I am running on HA on VMware workstation on Win10 I was not able to follow the solution mentioned from msanchezt right above.

**Comment by gryzli133** [comment]
I just found used/old OSK-102 on ebay and bough for about 20 Euro each. I think this is one of the easiest ways to get it up and running over LAN.

**Comment by thompssc** [comment]
> I just found used/old OSK-102 on ebay and bough for about 20 Euro each. I think this is one of the easiest ways to get it up and running over LAN.

Dumb question- does it have to be a "Midea" 102 module, or will a Pioneer or other work? Does it make any difference? I see many Pioneer OSK102 modules out there but no Mideas. I just got a U unit and it has the 103. I'd like to just put a 102 in there and be done with it.

**Comment by gryzli133** [comment]
@thompssc I also have other Module, not from Midea. At the end it doesnt metter, as long as the number is the same and it look similar then it will work. Good luck!

**Comment by thompssc** [comment]
> @thompssc I also have other Module, not from Midea. At the end it doesnt metter, as long as the number is the same and it look similar then it will work. Good luck!

Awesome, thanks!
