### ISSUE TITLE
midea_ac_886103000093 不可用

### ISSUE THREAD

**Issue by jingcard** [mac-zhou/midea-ac-py#51]
**Describe the bug （描述一下问题）**

midea_ac_886103000093 不可用

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题
![image](https://user-images.githubusercontent.com/36782030/106412147-f215b600-6481-11eb-80a8-3d1a8f390d26.png)
Update of climate.midea_ac_886103000093 is taking over 10 seconds
![image](https://user-images.githubusercontent.com/36782030/106412475-d19a2b80-6482-11eb-84bf-e16927fd469b.png)

**Versions (版本信息)**
 - Home Assistant version: 
版本 | 2021.1.5
安装类型 | Home Assistant OS
 - Midea msmart version:

**Comment by AlessandroTischer** [comment]
I think I have the same problem.

**Comment by mac-zhou** [comment]
请试试新版本

**Comment by mac-zhou** [comment]
try the new version
