### ISSUE TITLE
HA 2021.3 Gives warning over no version info in custom component

### ISSUE THREAD

**Issue by Dinges28** [mac-zhou/midea-ac-py#55]
**Describe the bug （描述一下问题）**
Since upgrading to HA 2021.3, the logfile gives a warning on this intergration

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'midea_ac'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'midea_ac'
请提交相关截图，日志，抓包让开发者能够更快的解决问题

**Versions (版本信息)**
 - Home Assistant version: 2021.3
 - Midea msmart version: c1bd84c

**Comment by 42Network** [comment]
Still happening with core-2021.3.2

2021-03-15 13:19:12 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'midea_ac'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'midea_ac'

**Comment by LouiS22** [comment]
Created a PR to fix this (it's not a bug though).

**Comment by LouiS22** [comment]
Just copy and paste te below into custom_components/midea_ac/manifest.json

"version": "0.0.0",

save, restart. 

Problem solved :)

**Comment by mac-zhou** [comment]
updated
