### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by michass** [mac-zhou/midea-ac-py#56]
Please add Breazeless+ functions for this plugin

**Comment by mac-zhou** [comment]
I don't know what you are talking about

**Comment by valerachuk** [comment]
I think, he means this AC: https://www.midea.com/global/Heating---Cooling/Breezeless

**Comment by mac-zhou** [comment]
> I think, he means this AC: https://www.midea.com/global/Heating---Cooling/Breezeless

thank you

**Comment by mac-zhou** [comment]
> Please add Breazeless+ functions for this plugin

try new version

**Comment by mac-zhou** [comment]
@michass 
```
pip3 install msmart
midea-discover
```
then, show me output
