### ISSUE TITLE
A/C Unavailable

### ISSUE THREAD

**Issue by AlessandroTischer** [mac-zhou/midea-ac-py#57]
**Describe the bug**
I followed the guide to integrate an Ariston A/C (Works with Midea's Servers, I use it through Midea's App), but the A/C results unavailable. IP and ID in configuration are correct. 
**Screenshots / Logs / Pcap File**
![image](https://user-images.githubusercontent.com/23379317/112615650-0beccd00-8e23-11eb-84be-51b02596ef33.png)

**Versions**
 - Home Assistant version: core-2021.2.3

@mac-zhou

**Comment by AlessandroTischer** [comment]
@rokam

**Comment by rokam** [comment]
Hey @AlessandroTischer , have you tried the new version?

You can use the keep_last_known_online_state configuration to maintain the last state.

**Comment by AlessandroTischer** [comment]
> Hey @AlessandroTischer , have you tried the new version?
> 
> You can use the keep_last_known_online_state configuration to maintain the last state.

I never had a last state😅
The integration never worked for me, and since a couple of hours ago because of some server updates the cloud version does not work anymore...

**Comment by rokam** [comment]
Were you able to run midea-discover?

**Comment by AlessandroTischer** [comment]
> Were you able to run midea-discover?

I didn't need it, since I'm outside of China I used midea app

**Comment by rokam** [comment]
Maybe Ariston A/C uses a different protocol, and this version communicates directly to the device using your lan. You might be able to use andersonshatch/midea-ac-py cause it uses the midea cloud to communicate with the device.

**Comment by AlessandroTischer** [comment]
> Maybe Ariston A/C uses a different protocol, and this version communicates directly to the device using your lan. You might be able to use andersonshatch/midea-ac-py cause it uses the midea cloud to communicate with the device.

It does not work anymore since today...

**Comment by rokam** [comment]
> > Were you able to run midea-discover?
> 
> I didn't need it, since I'm outside of China I used midea app

midea-discover try to communicate directly with the device through Lan. If your AC doesn't appear with midea-discover tool, this proves my theory of a different communication protocol.

**Comment by AlessandroTischer** [comment]
> > > Were you able to run midea-discover?
> > 
> > 
> > I didn't need it, since I'm outside of China I used midea app
> 
> midea-discover try to communicate directly with the device through Lan. If your AC doesn't appear with midea-discover tool, this proves my theory of a different communication protocol.

I found all my A/C marked as unsupported...

**Comment by AlessandroTischer** [comment]
Coud Fake-midea-cloud work?

**Comment by rokam** [comment]
Sorry, I don't know fake-midea-cloud.

**Comment by welo78** [comment]
@AlessandroTischer where did you found your device as unsupported ?

I am facing the same issue as you, I have a VIVAX AC and it uses net home plus app.

So far I am using a broadlink rm4 mini to operate the AC but it only sends packets and does not recieve them. Its like a remote.

**Comment by AlessandroTischer** [comment]
> @AlessandroTischer where did you found your device as unsupported ?
> 
> I am facing the same issue as you, I have a VIVAX AC and it uses net home plus app.
> 
> So far I am using a broadlink rm4 mini to operate the AC but it only sends packets and does not recieve them. Its like a remote.

You have to run msmart midea discover. It will show all the devices using midea's protocol and tell you if they are supported

**Comment by mac-zhou** [comment]
new version support 8370 and no need fake-midea-cloud.

**Comment by AlessandroTischer** [comment]
> new version support 8370 and no need fake-midea-cloud.



> new version support 8370 and no need fake-midea-cloud.

Is it possible to send you a private message somehow? I have some logs but I'm not sure about what's private and needs to be kept private...

**Comment by mac-zhou** [comment]
telegram group https://t.me/joinchat/UFSSaqBJE5RqvSOq
