### ISSUE TITLE
Unsupported device

### ISSUE THREAD

**Issue by Sonusss** [mac-zhou/midea-ac-py#59]
Hello,
My devices are detected as unsupported by midea discover...
Any option ?

INFO:msmart.cli:msmart version: 0.1.24
INFO:msmart.cli:Sending Device Scan Broadcast...
INFO:msmart.cli:Midea Local Data 192.168.122.135 837000b8200f04985a5a0111a8007a80000000000000000000000000dc580100001d0000000000000000000000000000d3db48a3ab89e7ecc0ab721e00b83fc6727ffa57ede4c280811d395889f0138da6e293ef7eccee7fa628311f09f5925ab90a62d4844fdb7558c94aec4f6de17c7bb675419ce56398b05af366fe71d616ea299df42bb39faf330f5ff8c078f38ef31443d17c3aac03a7656614ae1dca44e27c5ee009976716f124df1dbb03edb48db8d6d127eaedf9bdc88a9f782d52ef
INFO:msmart.cli:Decrypt Reply: 192.168.122.135 877aa8c02c19000030303030303050303030303030305131383437433942344235423345303030300b6e65745f61635f354233450000000001000000040000000000ac00000000000000847c9b4b5b3e069fcd0300060103010000000000000000000000000000000000000000
INFO:msmart.lan:Couldn't connect with Device 192.168.122.135:6444
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.122.135 - port: 6444 - id: 31885837293788 - sn: 000000P0000000Q1847C9B4B5B3E0000 - ssid: net_ac_5B3E
INFO:msmart.cli:Midea Local Data 192.168.122.100 837000b8200f043f5a5a0111a8007a800000000000000000000000004ae40200001100000000000000000000000000008d934e4f14b151b79e688ac2db2816676093d4a0cb2e94df40f0d6968bf53c5752343cee39a531b43dc9988eda7809878362e46318e23bbb0e8792ea260a0c397f9eb73bf5343b34211f922d5d42fd94ea299df42bb39faf330f5ff8c078f38ef31443d17c3aac03a7656614ae1dca44ce23b43a491d74e24fd88de508119ce39f77e0e46b192e1a425ce06b3466e979
INFO:msmart.cli:Decrypt Reply: 192.168.122.100 647aa8c02c19000030303030303050303030303030305131383437433942344139304642303030300b6e65745f61635f393046420000000001000000040000000000ac00000000000000847c9b4a90fb069fcd0300060103010000000000000000000000000000000000000000
INFO:msmart.lan:Couldn't connect with Device 192.168.122.100:6444
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.122.100 - port: 6444 - id: 18691697861706 - sn: 000000P0000000Q1847C9B4A90FB0000 - ssid: net_ac_90FB

**Comment by Sonusss** [comment]
Same info but with DEBUG mode:

midea-discover -d    
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.24
INFO:msmart.cli:Sending Device Scan Broadcast...
INFO:msmart.cli:Midea Local Data 192.168.122.100 837000b8200f04195a5a0111a8007a800000000000000000000000004ae40200001100000000000000000000000000008d934e4f14b151b79e688ac2db2816676093d4a0cb2e94df40f0d6968bf53c5752343cee39a531b43dc9988eda7809878362e46318e23bbb0e8792ea260a0c397f9eb73bf5343b34211f922d5d42fd94682b11e235eef961e588bd6fd663cf18f31443d17c3aac03a7656614ae1dca44d62d0021f8e6ad686061449bf062a7e49f77e0e46b192e1a425ce06b3466e979
INFO:msmart.cli:Decrypt Reply: 192.168.122.100 647aa8c02c19000030303030303050303030303030305131383437433942344139304642303030300b6e65745f61635f393046420000000001000000040000000000ac00000000000000847c9b4a90fb069fcd0300060103000000000000000000000000000000000000000000
DEBUG:msmart.command:Finalize request data: aa20ac00000000000003418100ff03ff000200000000000000000000000035ae89
DEBUG:msmart.lan:Sending to 192.168.122.100:6444 5a5a011168002000000000002735130a040415144ae40200001100000000000000000000000000006b000a76e27eed2c3647e57d8602df8bf1ca5b02d25a8cdb0c30be971fdb12777a6d2fd0aa2dbac5227e569b8730a9f55d0e994f561ab8586078e3c528f5cf2e
INFO:msmart.lan:Couldn't connect with Device 192.168.122.100:6444
DEBUG:msmart.device:refresh - Recieved from 192.168.122.100, 4ae402000011: 
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.122.100 - port: 6444 - id: 18691697861706 - sn: 000000P0000000Q1847C9B4A90FB0000 - ssid: net_ac_90FB
INFO:msmart.cli:Midea Local Data 192.168.122.135 837000b8200f041d5a5a0111a8007a80000000000000000000000000dc580100001d0000000000000000000000000000d3db48a3ab89e7ecc0ab721e00b83fc6727ffa57ede4c280811d395889f0138da6e293ef7eccee7fa628311f09f5925ab90a62d4844fdb7558c94aec4f6de17c7bb675419ce56398b05af366fe71d616682b11e235eef961e588bd6fd663cf18f31443d17c3aac03a7656614ae1dca44a1e04119985fe5c66cc2b71235e399f58db8d6d127eaedf9bdc88a9f782d52ef
INFO:msmart.cli:Decrypt Reply: 192.168.122.135 877aa8c02c19000030303030303050303030303030305131383437433942344235423345303030300b6e65745f61635f354233450000000001000000040000000000ac00000000000000847c9b4b5b3e069fcd0300060103000000000000000000000000000000000000000000
DEBUG:msmart.command:Finalize request data: aa20ac00000000000003418100ff03ff00020000000000000000000000000171fa
DEBUG:msmart.lan:Sending to 192.168.122.135:6444 5a5a011168002000000000003301140a04041514dc580100001d00000000000000000000000000006b000a76e27eed2c3647e57d8602df8bd756df0835cd44560eda34b9892d6087374ec39213ba414c4b7145c83c20f07f749dfa3a1b326399412fc57c48051e45
INFO:msmart.lan:Couldn't connect with Device 192.168.122.135:6444
DEBUG:msmart.device:refresh - Recieved from 192.168.122.135, dc580100001d: 
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.122.135 - port: 6444 - id: 31885837293788 - sn: 000000P0000000Q1847C9B4B5B3E0000 - ssid: net_ac_5B3E

**Comment by Sonusss** [comment]
What looks strange to me is that type is '0xac' which is supposed to be OK and I can get device_id and device_sn...

**Comment by 1179098689** [comment]
附议

**Comment by 1179098689** [comment]
> 在我看来，奇怪的是类型为“ 0xac”，应该可以，并且我可以获取device_id和device_sn ...

V3版本都用不了

**Comment by njordan77** [comment]
I'm having the same problem. Any idea how i can fix this. really desperate as i want to control the AC via LAN. Thanks
Norbert

INFO:msmart.cli:*** Found a unsupported '0xac' at 192.168.1.70 - id: 31883455458285 - sn: P000324543542B2370CDB4C0000 - ssid: net_ac_d5664

**Comment by Sonusss** [comment]
After having spent lot of time digging on forums I came to the conclusion that it seems to be a problem linked with extra security layer implemented in the WiFi dongle SK-103 while SK-102 doesn't have this security.
This info is just my clue not really proven.
However I made it with a totally other approach changing the genuine dongle for this one https://easyeda.com/aceindy/midea-open-dongle and a forked version of ESP-Home supporting Midea AC https://github.com/dudanov/esphome. It's working like a charm and BTW it is less expensive than the original dongle

**Comment by njordan77** [comment]
@Sonusss thanks a lot. that is more than great information. As i do a lot of ESP development that is an easy integration and much better than trying to make the instable stick communication work. Only one question, can you link me directly to the fork. I could only find an IR version but not the one directly replacing the STICK. Cheers and Thanks Norbert

**Comment by Sonusss** [comment]
@njordan77 Sorry maybe I'm coming late but if needed I can send you a small howto...
Won't publish here as our conversation is not related to this repo.

**Comment by njordan77** [comment]
@Sonusss 
could you please send me an email. norbert.jordan@gmail.com
as i do not have your contact details. will remove this message afterwards. thanks a lot.
