### ISSUE TITLE
midea integration error

### ISSUE THREAD

**Issue by Cireasa23** [mac-zhou/midea-ac-py#60]
Logger: homeassistant.loader
Source: loader.py:786
First occurred: 11:44:30 AM (1 occurrences)
Last logged: 11:44:30 AM

No 'version' key in the manifest file for custom integration 'midea_ac'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'midea_ac'

**Comment by Asom-Velz** [comment]
Same to me
Logger: homeassistant.loader
Source: loader.py:786
First occurred: 12:08:45 PM (1 occurrences)
Last logged: 12:08:45 PM

No 'version' key in the manifest file for custom integration 'midea_ac'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'midea_ac'

**Comment by LouiS22** [comment]
Guys, before posting the same thing again and again, have a look at the PR tab. I've placed the update there, we just have to wait the owner to accept is.

**Comment by Cireasa23** [comment]
Thank you, I will keep that in mind, I did not new what version to put but with 0.0.0 works with no errors.
Best regards,
