### ISSUE TITLE
AC is became UNAVAILABLE and connected again

### ISSUE THREAD

**Issue by adizag** [mac-zhou/midea-ac-py#62]
Hi

I'm using this integration for a long time.
a couple of months ago the ACs started to have a strange behavior like going on and off in the HA panel. You can see this in the attached video.
That is causing problems with automations of course.
what could be wrong?

![image](https://user-images.githubusercontent.com/17390016/117554576-445a0a80-b061-11eb-9e0e-032540de7b3d.png)

https://user-images.githubusercontent.com/17390016/117554469-a2d2b900-b060-11eb-8307-94a86e034f07.mp4

**Comment by willyhabr** [comment]
Same behavior here in my hass

**Comment by captennemo** [comment]
Same here.

**Comment by msanchezt** [comment]
Same for me I get alerts like: "AC Day Zone state changed to: unavailable" and it recovers after few minutes.

 Question is: is this related to this integration? Or it's something related with the USB dongle? Have anyone tried to remove/disable integration and see if it gets fixed?

**Comment by adizag** [comment]
I tried - no help.
The dongle is probably OK, the android app doesn't dhow any disconnection...

I hope the developer will make contact...

בתאריך יום ב׳, 7 ביוני 2021, 11:14, מאת msanchezt ***@***.***

**Comment by msanchezt** [comment]
Are you sure about the android app not showing any disconnection? In my case, whenever I receive the "unavailable" state from Home Assistant I go straight to check the app and I see the device offline. 

It gets resolved just by waiting few minutes, by power cycling the device or by rebooting the Access point (meaning forcing the device to reconnect to wifi). 

Funny thing is that even the device shows "unavailable" on HA and "offline" on android App I can ping the IP of the device, meaning is connected to wifi still. 

Very strange, and not sure how to do some more investigation

**Comment by adizag** [comment]
@msanchezt - THAT problem is a real problem. it is a problem with the dongle probably, and to solve it I do the same as you - power cycle the device and it is alive again. that problem was always with the Midea AC...

The problem this ticket is referring is HA problem, as you can see in the video - the ACs are toggling  from online to unavailable all of the time.

anyway, until @mac-zhou will check and fix it, I **solved it by going back to the former integration** I worked with (through the Midea cloud) and it works flawlessly.
[](https://github.com/andersonshatch/midea-ac-py)  
https://github.com/andersonshatch/midea-ac-py

the configuration is as the following:
```
climate:
      platform: midea
      app_key: 3742e9e5842d4ad59c2db887e12449f9
      username: !secret midea_user
      password: !secret midea_pass
```

**Comment by mac-zhou** [comment]
The reason for this problem is that midea-msmart(version 0.1.24) use the dongle response as the AC's status.
Sometimes the dongle does not respond.
you can add `scan_interval: 60` to configure file and see if it still happens.

**Comment by mac-zhou** [comment]
Here is a discussion about this issue #43

**Comment by mac-zhou** [comment]
> Where would you add this line, please?

```climate:
  - platform: midea_ac
    host: 192.168.1.100
    id: 123456789012345
    scan_interval: 60
```

**Comment by adizag** [comment]
@mac-zhou that wouldn't help, just spacing the time between the status changes...
I changed midea-msmart (version 0.1.24) to 0.1.23 as explained in #42 . Now it is working for me.

TNX!

**Comment by mac-zhou** [comment]
The actual is still UNAVAILABLE, v0.1.23 uses the old state. I'm considering adding an option to be compatible.

**Comment by adizag** [comment]
@mac-zhou **I think it would be necessary**. For me, it is working well.
The only problem when the AC is not connected is that it shows 0° (or maybe the last read temp?). Anyway, that is much better than having this unavailable status going on and off all of the time, because I already have other measures to check if the AC is online - I ping all ACs every minute.
