### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by antonioloi1984** [mac-zhou/midea-ac-py#63]
**Describe the bug （描述一下问题）**

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题

**Versions (版本信息)**
 - Home Assistant version: Home Assistant 2021.5.1
 - Midea msmart version: last

Logger: homeassistant.loader
Source: loader.py:794
First occurred: 16:01:14 (1 occurrences)
Last logged: 16:01:14

No 'version' key in the manifest file for custom integration 'midea_ac'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'midea_ac'

**Comment by pathia** [comment]
As a temporary fix we could add
`, "version": "0.1.24"`
before the closing curly brace on the last line of manifest.json

**Comment by mac-zhou** [comment]
updated
