### ISSUE TITLE
Air Con - no state

### ISSUE THREAD

**Issue by JamieP83** [mac-zhou/midea-ac-py#71]
**Describe the bug （描述一下问题）**
Everything seems to have installed OK, nothing in the logs.
However im not getting any state for my device?
it works fine via the mobile app?

model: Midea 12000 BTU Portable Air Conditioning Unit With Wi-Fi - MPPFB1-12CRN7 

For me logs i have this in my config yaml
`custom_components.midea_ac: debug`
nothing to be found however

**Versions (版本信息)**
 - Home Assistant version: 2021.7.2
 - Midea msmart version: 8d9ea67 (latest via HACS)

![image](https://user-images.githubusercontent.com/48566948/125704032-eec02c3b-9ba7-439a-8951-9129ff91be76.png)

**Comment by sbGoogle** [comment]
II also have the same problem.. Midea Blanc MA-18N8D0/NXD0-I

![image](https://user-images.githubusercontent.com/16179847/125746829-6760934b-9113-421e-8e7a-91c459bae5bb.png)

![image](https://user-images.githubusercontent.com/16179847/125746879-88ee14f9-0664-4e8a-b1bc-1abb0c0fd62e.png)

**Comment by mac-zhou** [comment]
show me the homeassistant log

**Comment by mac-zhou** [comment]
and show me `midea-discover` output
