### ISSUE TITLE
VIVAX Compatibility

### ISSUE THREAD

**Issue by welo78** [mac-zhou/midea-ac-py#72]
Is there any possibility of VIVAX AC integration ? It uses the same app Net Home Plus.

I tried connecting it but it seems that the entitiy is unavailable. Does it use some kind of other communication protocol?

**Comment by fpetrovski** [comment]
I've got a vivax AC and have been using this integration for almost a year.

On the latest version, the integration breaks so use the version before that.

**Comment by mac-zhou** [comment]
You need to tell me more detailed information

**Comment by mac-zhou** [comment]
such like homeassistant log

**Comment by fpetrovski** [comment]
I just updated to the latest version and seems all is working fine now.

I don't remember the exact version with which I had problems, but seeing it's working now, please ignore my previous comment.
