### ISSUE TITLE
Broken after home assistant version update

### ISSUE THREAD

**Issue by CristiCostache** [mac-zhou/midea-ac-py#75]
Hi,
After upgrading to latest version of home assistant, the ac's stopped working (all are in unavailable state).
The midea-discover finds all units and it's seeing as supported devices.
`INFO:msmart.cli:*** Found a supported 'ac' (0) at 192.168.0.250:6444 - id: 318845444441068 - sn: 00054532343xxxxx5A0000 - ssid: net_ac_0E5A - mac: a06xxxxxxe5a - protocol: 3`

I already have the fake cloud service installed and configured. I tried to roll back previous version but unfortunately it doesn't work anymore.
I saw is required for the third version to configure k1 option. Where do I get this id?

**Versions (版本信息)**
 - Home Assistant version: core-2021.8.5
 - Midea msmart version:  0.1.20

**Comment by yevon** [comment]
Same here, not working after update. Another question, would it be possible to get air conditioner consumption in watts or kwh? That would be awesome.

**Comment by mac-zhou** [comment]
your `midea-discover` is not my version, please install new version.
read the README.md to get token and k1
@CristiCostache

**Comment by mac-zhou** [comment]
> Same here, not working after update. Another question, would it be possible to get air conditioner consumption in watts or kwh? That would be awesome.

what's your device's version.V2 or v3?

**Comment by yevon** [comment]
My version is v2, until now I didn't need token or k1. I will try to downgrade to see if this solves the issue

**Comment by yevon** [comment]
I have two air conditioners, and it seems that one of them is unreachable, the other one is ok. Is it possible that if I have two and one fails, the other doesn't get updated?

![image](https://user-images.githubusercontent.com/121157/129177937-e9ec3d0b-7e60-4cdf-8078-6ed459e8c683.png)

**Comment by mac-zhou** [comment]
show me the `midea-discover` output

**Comment by yevon** [comment]
![image](https://user-images.githubusercontent.com/121157/129180137-136ba53d-a66b-4d9b-9587-261aace5a9bb.png)

**Comment by yevon** [comment]
I think I cannot downgrade as hacs doesn't allow me to see the versions select list for this extension.

**Comment by rokam** [comment]
I'm with the same issue.  @mac-zhou can you please create a release for each version inside github? That way we'll be able to downgrade to the previous version.

**Comment by mac-zhou** [comment]
1. @CristiCostache installed is not my project.
2. I am also using the v2 version myself, there is no problem.
3. the network problem can happen no matter what version it is.

**Comment by mac-zhou** [comment]
> I'm with the same issue (v2 not working). @mac-zhou can you please create a release for each version inside github? That way we'll be able to downgrade to the previous version.

show me your debug log

**Comment by mac-zhou** [comment]
Use Android  emulator ,  readme have the link. https://en.ldplayer.net/?from=en

**Comment by CristiCostache** [comment]
> Use Android emulator , readme have the link. https://en.ldplayer.net/?from=en

Thanks for the hint Mac. 
After getting the k1 and token the problems still persists.

`INFO:msmart.cli:Midea Local Data 192.168.0.251 837000b8200f04025a5a0111a8007a80000000000000000000000000a5fe7227acff0000000000000000000000000000f5673684d4007bf21538d02e8605d2acb2d75b480d763883fdfbc16c5af92594c28f29a40e57a10f45b209b271740dfed5519f260bbf320e0ce62d820435a8124947ad348e1a739ee28a65ade9876a090d9b07edb0b5f9e45adf43bc6c900a28f31443d17c3aac03a7656614ae1dca446cfc0de1bf3b5cd25e27b24915dc2fa300000000000000000000000000000000
INFO:msmart.cli:Decrypt Reply: 192.168.0.251 fb0011ac2c19000030303030303050303030303030305131413036383143313437453344303030300b6e65745f61635f374533440000000001000000040000000000ac00000000000000a0681c147e3d069fcd0300080003000000000000000000000000000000000000000000
INFO:msmart.lan:Couldn't connect with Device 192.168.0.251:6444
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.0.251 - port: 6444 - id: 281113232323239 - upid: 3cc6e4c3314a9b32433edcxxxxxxx4dfb - sn: 000000P0000000Q1A06xxxxxxxx0000 - ssid: net_ac_7E3D
INFO:msmart.cli:+++ This device( 192.168.0.251 ) needs more information to support, open https://github.com/mac-zhou/midea-ac-py`

mdsmart version : `root@automations:~# midea-discover
INFO:msmart.cli:msmart version: 0.1.28
INFO:msmart.cli:Sending Device Scan Broadcast...
`

**Comment by mac-zhou** [comment]
It should be that what I described is not very clear, I will change this message.
You no longer need to use midea-discover, you can go directly to configure.
like:
```yaml
climate:
  - platform: midea_ac
    host: 192.168.1.100
    id: 123456789012345
    # v3 need token and id
    token: ACEDDA53831AE5DC...(Length 128)
    k1: CFFA10FC...(Length 64)
```

**Comment by rokam** [comment]
> > I'm with the same issue (v2 not working). @mac-zhou can you please create a release for each version inside github? That way we'll be able to downgrade to the previous version.
> 
> show me your debug log

`
2021-08-12 14:03:11 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_ac_12094627963550 fails
Traceback (most recent call last):
  File "/home/kodi/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/home/kodi/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/home/kodi/.homeassistant/custom_components/midea_ac/climate.py", line 133, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/home/kodi/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/kodi/homeassistant/lib/python3.8/site-packages/msmart/device.py", line 195, in refresh
    self._send_cmd(cmd)
  File "/home/kodi/homeassistant/lib/python3.8/site-packages/msmart/device.py", line 204, in _send_cmd
    responses = self._lan_service.appliance_transparent_send(data)
  File "/home/kodi/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 102, in appliance_transparent_send
    response = self.request(data)
  File "/home/kodi/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 42, in request
    self._connect()
  File "/home/kodi/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 33, in _connect
    raise error
  File "/home/kodi/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 30, in _connect
    self._socket.connect((self.device_ip, self.device_port))
socket.timeout: timed out
`

**Comment by mac-zhou** [comment]
@CristiCostache no need

**Comment by mac-zhou** [comment]
@rokam @yevon I should know why. I should not use `raise error`
Fix in the next version

**Comment by mac-zhou** [comment]
try new version msmart==0.1.29

**Comment by mac-zhou** [comment]
@CristiCostache Is the new version running normally?

**Comment by yevon** [comment]
Wow I didn't understand the release notes of "naming changed", device id has changed, it was that in my case.

**Comment by rokam** [comment]
For me, is working fine now.

**Comment by CristiCostache** [comment]
> @CristiCostache Is the new version running normally?

Unfortunately not.

```Logger: homeassistant.components.climate
Source: custom_components/midea_ac/climate.py:79
Integration: Climate (documentation, issues)
First occurred: 4:37:46 PM (1 occurrences)
Last logged: 4:37:46 PM

Error while setting up midea_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/midea_ac/climate.py", line 79, in async_setup_platform
    device.authenticate(device_k1, device_token)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 49, in authenticate
    self._authenticate()
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 52, in _authenticate
    self._lan_service.authenticate(self._token, self._key)
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 74, in authenticate
    response = self.request(request)[8:72]
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 42, in request
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 33, in _connect
    raise error
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 30, in _connect
    self._socket.connect((self.device_ip, self.device_port))
socket.timeout: timed out
```

**Comment by mac-zhou** [comment]
> Wow I didn't understand the release notes of "naming changed", device id has changed, it was that in my case. I changed it and now works

sorry, my description is not very clear. my english is not good. can you help me ? :)

**Comment by mac-zhou** [comment]
> > @CristiCostache Is the new version running normally?
> 
> Unfortunately not.
> 
> ```
> Source: custom_components/midea_ac/climate.py:79
> Integration: Climate (documentation, issues)
> First occurred: 4:37:46 PM (1 occurrences)
> Last logged: 4:37:46 PM
> 
> Error while setting up midea_ac platform for climate
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/midea_ac/climate.py", line 79, in async_setup_platform
>     device.authenticate(device_k1, device_token)
>   File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 49, in authenticate
>     self._authenticate()
>   File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 52, in _authenticate
>     self._lan_service.authenticate(self._token, self._key)
>   File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 74, in authenticate
>     response = self.request(request)[8:72]
>   File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 42, in request
>     self._connect()
>   File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 33, in _connect
>     raise error
>   File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 30, in _connect
>     self._socket.connect((self.device_ip, self.device_port))
> socket.timeout: timed out
> ```

it's not new version, please update.

**Comment by CristiCostache** [comment]
```root@automations:~# midea-discover
INFO:msmart.cli:msmart version: 0.1.29
```

**Comment by mac-zhou** [comment]
in your log:
 ` File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 33, in _connect
    raise error`
but new version line 33:
https://github.com/mac-zhou/midea-msmart/blob/1b38d8d19a1d4e615ec58a44935294bfa28feba7/msmart/lan.py#L33

**Comment by mac-zhou** [comment]
@CristiCostache any errors？

**Comment by CristiCostache** [comment]
Hi Mac,

Still not working. 

```Logger: homeassistant.components.climate
Source: custom_components/midea_ac/climate.py:79
Integration: Climate (documentation, issues)
First occurred: 8:06:49 AM (1 occurrences)
Last logged: 8:06:49 AM

Error while setting up midea_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/midea_ac/climate.py", line 79, in async_setup_platform
    device.authenticate(device_k1, device_token)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 49, in authenticate
    self._authenticate()
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 52, in _authenticate
    self._lan_service.authenticate(self._token, self._key)
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 81, in authenticate
    raise error
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 76, in authenticate
    tcp_key = self.security.tcp_key(response, self._key)
  File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 91, in tcp_key
    raise Exception('authentication failed')
Exception: authentication failed
```

**Comment by mac-zhou** [comment]
your token and k1 is wrong.

**Comment by jmadejek** [comment]
I have the same sittuation, ver 2

`INFO:msmart.cli:msmart version: 0.1.29
INFO:msmart.cli:Sending Device Scan Broadcast...
INFO:msmart.cli:Midea Local Data 192.168.1.69 5a5a011178007a800000000000000000000000001abf0100001100000000000000000000010000006d659c0df0a1e8113624a17df02d0c9e14e5b5ed3bbf4cad79b413d7ec2b87a4408f4f04fac3281efa4e1ef57e0d37ba52c0229ff1b9b7b3ff01e5143d9ad61cf73f91a37161ac27a13803cc0f64a232
INFO:msmart.cli:Decrypt Reply: 192.168.1.69 4501a8c02c19000030303030303050303030303030305131333435424242314243423733303030300b6e65745f61635f43423733
INFO:msmart.cli:*** Found a supported device - type: '0xac' - version: V2 - ip: 192.168.1.69 - port: 6444 - id: 18691697786650 - sn: 000000P0000000Q1345BBB1BCB730000 - ssid: net_ac_CB73.
INFO:msmart.cli:Midea Local Data 192.168.1.67 5a5a011178007a800000000000000000000000005bab010000110000000000000000000001000000b3ca2889f518650789537f9bb7f7824c14e5b5ed3bbf4cad79b413d7ec2b87a48fdcb730217f3b9f7fd3cff425d7f4fe759b97c2b66fa00d36d0236bfbd5b121833d595947c5a3f21f3bc0562c4f11c6
INFO:msmart.cli:Decrypt Reply: 192.168.1.67 4301a8c02c19000030303030303050303030303030305131333435424242314243393239303030300b6e65745f61635f43393239
INFO:msmart.cli:*** Found a supported device - type: '0xac' - version: V2 - ip: 192.168.1.67 - port: 6444 - id: 18691697781595 - sn: 000000P0000000Q1345BBB1BC9290000 - ssid: net_ac_C929.
INFO:msmart.cli:Midea Local Data 192.168.1.71 5a5a011178007a80000000000000000000000000c931000000140000000000000000000001000000dbdeb9694ed956a761b72365c45236b8af6ae8e9c5c9c57a9a8add7f9641e96c9d78dee1fbefa036eb063297f3fc48b167cfea26d43525acab75071e6a246315fea02f1beafd0b905fe263dacc026b3a
INFO:msmart.cli:Decrypt Reply: 192.168.1.71 4701a8c02c19000030303030303050303030303030305131463043394431424641383934303030300b6e65745f61635f41383934
INFO:msmart.cli:*** Found a supported device - type: '0xac' - version: V2 - ip: 192.168.1.71 - port: 6444 - id: 21990232568265 - sn: 000000P0000000Q1F0C9D1BFA8940000 - ssid: net_ac_A894.
`
ID is correct

After downgrading (0.1.25) all works perfect. After upgrading there is no connection

My config:

`climate:
  - platform: midea_ac
    host: 192.168.1.71
    id: 21990232568265
    prompt_tone: false

  - platform: midea_ac
    host: 192.168.1.69
    id: 18691697786650
    prompt_tone: false

  - platform: midea_ac
    host: 192.168.1.67
    id: 18691697781595
    prompt_tone: false
`

**Comment by rokam** [comment]
@jmadejek the entities changed the name after ver 0.1.27. So your old entities should appear as unavailable

**Comment by jmadejek** [comment]
> @jmadejek the entities changed the name after ver 0.1.27. So your old entities should appear as unavailable

Yes, README.md is updated, and now all is clear. Thank you!

**Comment by nashant** [comment]
Mine's not working either. 
Debug logs from midea-discover:
```
# midea-discover -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.29
INFO:msmart.cli:Sending Device Scan Broadcast...
INFO:msmart.cli:Midea Local Data 172.16.0.210 5a5a011178007a80000000000000000000000000e791010000110000000000000000000001000000bea3af319a4b361fd31d7aa61ebbb9423da037d34731c198667d0a5bd3a6b98e7d24298602e582aaf7ee0fe852fcfd7403871a2846f4aac52bc80c1002bd837dbd5399df2a70017468047fa3a2549a05
INFO:msmart.cli:Decrypt Reply: 172.16.0.210 d20010ac2c19000030303030303050303030303030305131463043394431453344424336303030300b6e65745f61635f44424336
DEBUG:msmart.command:Finalize request data: aa20ac00000000000003418100ff03ff00020000000000000000000000002f4df0
DEBUG:msmart.device:pkt_builder: 172.16.0.210:172.16.0.210 len: 104 data: 5a5a01116800200000000000162f140714081514e7910100001100000000000000000000000000006b000a76e27eed2c3647e57d8602df8bcef2bff4f6df0c6d5010e41fad569e541fd6a683c4596e94e3233ba3eca33e4ed8d4c201a356e6bf0a434895143968e7
DEBUG:msmart.lan:Attempting new connection to 172.16.0.210:6444
DEBUG:msmart.lan:Sending to 172.16.0.210:6444 5a5a01116800200000000000162f140714081514e7910100001100000000000000000000000000006b000a76e27eed2c3647e57d8602df8bcef2bff4f6df0c6d5010e41fad569e541fd6a683c4596e94e3233ba3eca33e4ed8d4c201a356e6bf0a434895143968e7
DEBUG:msmart.lan:Received from 172.16.0.210:6444 5a5a011168002080000000000000000000000000e791010000110000000000000000000001000000d1743e366382410904e8afbba3f6b46649375e7a089a6b1aaedd6a167994e8d45473611ef48db5c5a3f80ceae55a6cb86f31e13421482cd27b5be8a70181b5b2
DEBUG:msmart.lan:Got responses len: 104
DEBUG:msmart.device:Got responses from 172.16.0.210:172.16.0.210 Version: 2 Count: 1
DEBUG:msmart.device:Update from 172.16.0.210:172.16.0.210 aa22ac00000000000303c000413c0000003000000066ff000000000000000000f0dd8d
DEBUG:msmart.command:Appliance response data: c000413c0000003000000066ff000000000000000000f0dd8d
INFO:msmart.cli:*** Found a supported device - type: '0xac' - version: V2 - ip: 172.16.0.210 - port: 6444 - id: 18691697775079 - sn: 000000P0000000Q1F0C9D1E3DBC60000 - ssid: net_ac_DBC6.
```

Setting
```
default: warn
logs:
  custom_components.midea_ac: debug
```
in my hass config doesn't seem to give me any debug logging

**Comment by mac-zhou** [comment]
> 
> Setting
> 
> ```
> default: warn
> logs:
>   custom_components.midea_ac: debug
> ```
> 
> in my hass config doesn't seem to give me any debug logging

```yaml
default: warn
logs:
  custom_components.midea_ac: debug
  msmart: debug
```

**Comment by nashant** [comment]
Got it, managed to fix. Thanks!

**Comment by mac-zhou** [comment]
If you still have problems, please reopen this issue
