### ISSUE TITLE
Can't Install Midea-Air-gettoken-only-oversea.apk App

### ISSUE THREAD

**Issue by Jonatino** [mac-zhou/midea-ac-py#76]
**Describe the bug （描述一下问题）**
Trying to install the Midea-Air-gettoken-only-oversea.apk on the README but it wont install on my Samsung S21 Ultra. It says "App not installed".

**Comment by Jonatino** [comment]
Is this a modified APK or will the official apk work as well for the log messages?

**Comment by dilscallion** [comment]
Same issue here on my Samsung S20

**Comment by pgsylvestre** [comment]
Same issue here on Samsung Note 20 from Canada

**Comment by mac-zhou** [comment]
try the new apk

**Comment by pgsylvestre** [comment]
Still Can't be installed

**Comment by mac-zhou** [comment]
> Still Can't be installed
Android 11?
you need to uninstall the old app, first
can you provide more information.
