### ISSUE TITLE
ClimateDevice is deprecated, modify MideaClimateACDevice to extend ClimateEntity HA 0.110

### ISSUE THREAD

**Issue by gkilcaus** [mac-zhou/midea-ac-py#8]
**Describe the bug （描述一下问题）**
There is a message in the logs that ClimateDevice is deprecated

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:547
Integration: Climate (documentation, issues)
First occurred: 8:16:51 PM (1 occurrences)
Last logged: 8:16:51 PM

ClimateDevice is deprecated, modify MideaClimateACDevice to extend ClimateEntity

**Versions (版本信息)**
 - Home Assistant version: 0.110.1
 - Midea msmart version: 0.1.12

**Comment by mac-zhou** [comment]
there is warning log in the new version(0.102.2), but it is better to let more people use it.
i will update it later
