### ISSUE TITLE
Constant "unavailable device"after last update of Midea Smart Aircon(25.08.2021)

### ISSUE THREAD

**Issue by mihaitaiosub** [mac-zhou/midea-ac-py#85]
After last update from today,25.08.2021,my two devices appears frequent and constantly unavailable.Until today works like a charm with previous updates.

[Configuration - Home Assistant.pdf](https://github.com/mac-zhou/midea-ac-py/files/7045174/Configuration.-.Home.Assistant.pdf)

**Versions (版本信息)**
 - Home Assistant version: 3.7.1
 - Midea msmart version: ca5b583

**Comment by panste13** [comment]
Hi I dont know if it is related but it seems to be an issue with midea-discover as well (with or without -a -p)

>midea-discover
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\midea-discover.exe\__main__.py", line 4, in <module>
  File "c:\python39\lib\site-packages\msmart\cli.py", line 13, in <module>
    from msmart.cloud import cloud
  File "c:\python39\lib\site-packages\msmart\cloud.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by mac-zhou** [comment]
pip3 install requests

**Comment by mihaitaiosub** [comment]
What does pip3 mean?

**Comment by mac-zhou** [comment]
> What does pip3 mean?

command to install requests module
```shell
pip3 install requests
```
or 
```shell
pip install requests
```

**Comment by mac-zhou** [comment]
> After last update from today,25.08.2021,my two devices appears frequent and constantly unavailable.Until today works like a charm with previous updates.
> 
> [Configuration - Home Assistant.pdf](https://github.com/mac-zhou/midea-ac-py/files/7045174/Configuration.-.Home.Assistant.pdf)
> 
> **Versions (版本信息)**
> 
> * Home Assistant version: 3.7.1
> * Midea msmart version: [ca5b583](https://github.com/mac-zhou/midea-ac-py/commit/ca5b583e2b26099950e507586c28656c861b9cb9)

You can ignore warning message.
If there are a lot of errors, I may need you to provide more logs.
actually， old version also has this information, but the new version outputs these logs.

**Comment by mihaitaiosub** [comment]
Update msmart==0.1.3 from 5days ago works fine,whitout any bug.

**Comment by mihaitaiosub** [comment]
Hello,it seems to be fine after update. Congratulations, you managed to solve the problem. Thank you for your work.
