### ISSUE TITLE
Midea AC does not receive or delay commands from the Home Assistant

### ISSUE THREAD

**Issue by mihaitaiosub** [mac-zhou/midea-ac-py#90]
After update to 278f021,my midea ac devices does not receive commands when i do in Home Assistant,or receive commands after 15-20 minutes.If I give commands immediately after I restart the Home Assistant, the commands
 are received immediately by the devices. After about 30 minutes, if I give other commands, the devices receive them only after 10-15 minutes or maybe not at all. The same thing happens if I reinstall Midea AC integration.

**Versions (版本信息)**
 - Home Assistant version: 2021.8.8
[Configuration - Home Assistant.pdf](https://github.com/mac-zhou/midea-ac-py/files/7071969/Configuration.-.Home.Assistant.pdf)

 - Midea msmart version: 278f021

**Comment by mstefanowicz** [comment]
I have the same problem. The commands are executed after 20-30 seconds.

**Comment by mihaitaiosub** [comment]
You're lucky, they react to me after 10-15 minutes.

**Comment by mac-zhou** [comment]
lan.py on line 70, add code, like:
```python
            _LOGGER.error("Send {} Error: {}".format(self.get_socket_info(), error))
            return bytearray(0), True
```

**Comment by mac-zhou** [comment]
it will be fix in the next version

**Comment by mac-zhou** [comment]
when send error,  forgot to return 😭

**Comment by mac-zhou** [comment]
update new version `37d64c8`

**Comment by mac-zhou** [comment]
If there is still a problem，please add to configs and give me home-assistant.log
```yaml
logger:
  default: info
  logs:
    custom_components.midea_ac: debug
    msmart: debug
```

**Comment by mihaitaiosub** [comment]
I made the update and I will keep you updated. Thank you.

**Comment by mac-zhou** [comment]
> I made the update and I will keep you updated. Thank you.

any errors now?

**Comment by mihaitaiosub** [comment]
Hello,only now, everything works without any mistakes. Congratulations and hopefully it will never go wrong again. I tested everything heavy,that is the cause for my late answer.Thank you very much!

**Comment by mstefanowicz** [comment]
I confirm, no problems.
