### ISSUE TITLE
midea-discover -a YOUR_ACCOUNT  YOUR_ACCOUNT不能手机号，提示this account does not exist'

### ISSUE THREAD

**Issue by iChenlife** [mac-zhou/midea-ac-py#93]
midea-discover -a YOUR_ACCOUNT -p YOUR_PASSWORD
YOUR_ACCOUNT 是手机号，会提示

\msmart\cloud.py", line 220, in throw
    raise ValueError(error_code, message)
ValueError: (3102, 'this account does not exist')

**Comment by mac-zhou** [comment]
账号当然不存在，登录的是海外美的APP
你需要注册个账号即可，不需要添加设备，在README中给出链接了
