### ISSUE TITLE
I don't understand at all what to do and ask for help!

### ISSUE THREAD

**Issue by SebastianStorb** [mac-zhou/midea-ac-py#97]
**Describe the bug （描述一下问题）**

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题

**Versions (版本信息)**
 - Home Assistant version: Home Assistant 2021.9.1
 - Midea msmart version: 0.1.27 (unter HACS) / 
 - 0.1.35 unter cloud.py
 - debian 11
 
I am a beginner and I cannot cope with the instructions. I have installed the Home Assistant, HACS, Midea Smart and MideaAccount. The ACs works fine with the AppStore App.

**I've tried so many settings that I can't report everything anymore**. So here's just an example:

Then checked that under
`nano /usr/local/lib/python3.9/dist-packages/msmart/cloud.py`
the following changes have been made:
`self.login_account = sebastian@###########`
self.password = ########meinKennwort

`root@debian-server:~# midea-discover -a sebastian@meineEmail -p #########meinKennwort
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
Traceback (most recent call last):
  File "/usr/local/bin/midea-discover", line 8, in <module>
    sys.exit(discover())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in __c                                                                             all__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1062, in mai                                                                             n
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in inv                                                                             oke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 763, in invo                                                                             ke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/msmart/cli.py", line 43, in disco                                                                             ver
    found_devices = loop.run_until_complete(discovery.get_all())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_compl                                                                             ete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 179, in                                                                              get_all
    [self.result.add(task.result()) for task in tasks]
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 179, in                                                                              <listcomp>
    [self.result.add(task.result()) for task in tasks]
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 42, in s                                                                             upport_test
    _device = await self.support_testv3(account, password)
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 57, in s                                                                             upport_testv3
    token, key = await loop.run_in_executor(None, gettoken, udpid, account, pass                                                                             word)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 232, in                                                                              gettoken
    Client = cloud(account, password)
  File "/usr/local/lib/python3.9/dist-packages/msmart/cloud.py", line 29, in __i                                                                             nit__
    self.login_account = sebastian@#####   # Your email address for your Mid                                                                             ea account
NameError: name 'sebastian' is not defined
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<scandevice.support_test() done, defin                                                                             ed at /usr/local/lib/python3.9/dist-packages/msmart/scanner.py:40> exception=Nam                                                                             eError("name 'sebastian' is not defined")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 42, in s                                                                             upport_test
    _device = await self.support_testv3(account, password)
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 57, in s                                                                             upport_testv3
    token, key = await loop.run_in_executor(None, gettoken, udpid, account, pass                                                                             word)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 232, in                                                                              gettoken
    Client = cloud(account, password)
  File "/usr/local/lib/python3.9/dist-packages/msmart/cloud.py", line 29, in __i                                                                             nit__
    self.login_account = sebastian@######   # Your email address for your Mid                                                                             ea account
NameError: name 'sebastian' is not defined
root@debian-server:~#
`
Another example:
`configuration.yaml:`
```
# Midea_AC
climate:
  platform: midea_ac
  host: 192.168.1.51
  id: Q1502DBB59E5C4000       # i dont know the right numer, just tested
```
`Invalid config for [climate.midea_ac]: [host] is an invalid option for [climate.midea_ac]. Check: climate.midea_ac->host. (See ?, line ?).`

No differenz here:

```
# Midea_AC
climate:
  - platform: midea_ac
    host: 192.168.1.51
    id: Q1502DBB59E5C4000
```
`Invalid config for [climate.midea_ac]: [host] is an invalid option for [climate.midea_ac]. Check: climate.midea_ac->host. (See ?, line ?).`

What can I do? 

Regards

**Comment by mac-zhou** [comment]
midea cloud's response is clear, your account is not defined.
just run `midea-discover`

**Comment by SebastianStorb** [comment]
Dear Mr. mac-zhou,

thank you very much for your answer. 
what i did:
1. ) remove and reinstall everything
2. ) `midea-discover` did not work:
`sebastian@debian-server:~$ midea-discover
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
Traceback (most recent call last):
  File "/home/sebastian/.local/bin/midea-discover", line 8, in <module>
    sys.exit(discover())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)`
3. ) `sebastian@debian-server:~$ midea-discover -a sebastian@####### -p ######## -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:msmart.scanner:Broadcast message sent: 0
DEBUG:msmart.scanner:Midea Local Data 192.168.1.41 837000b8200f05815a5a0111a8007a800000000000000000000000001ddf010000110000000000000000000000000000984d00b2d4c9263d389dcba34c333c0d7c5179b1de29da3850d76d9beb6696c409d094ea8b5ab078c36ae5db0d63e565500a7ef43d08fc8f1f9d1c4e319efd2f3e5cce0f502b5f189b3079db949718481fca94541303884c52e880ddefc03190f31443d17c3aac03a7656614ae1dca44c01f78a2478cdd96b622daeb5b47d866a7759d2f40f4337298b27ea5c7a4d798
DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.41 2901a8c02c19000030303030303050303030303030305131353032444242353945354334303030300b6e65745f61635f453543340000000001000000040000000000ac00000000000000502dbb59e5c4069fcd0300080103000000000000000000000000000000000000000000
DEBUG:msmart.scanner:Midea Local Data 192.168.1.51 837000b8200f04095a5a0111a8007a800000000000000000000000006938000000150000000000000000000000000000645bc8591e768667ddb4a5ea4106d21a7ea68da00601c5f2f7d7a54947ac851205c86e0c675124c4a3b3666b7c466968724a475e8584b76ad83ef522d6cbf8e9f6e1ffd30d0527659e7e6e507cf066981fca94541303884c52e880ddefc03190f31443d17c3aac03a7656614ae1dca44544d657e733532af39d28bf238602a7cfbf6563ba8bcb1c7b3cd63a4015cd50f
DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.51 3301a8c02c19000030303030303050303030303030305131353032444242343438383846303030300b6e65745f61635f383838460000000001000000040000000000ac00000000000000502dbb44888f069fcd0300080103000000000000000000000000000000000000000000
DEBUG:msmart.scanner:Socket timeout
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"###################################"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"##################"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"password error，please enter again.","errorCode":"3101"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"c537f5ef-8daf-4480-ade5-ae94e563c5e8"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"sebastian@##########","sessionId":"##################","accessToken":"####################","userId":"############","versionCode":"","leftCount":""},"errorCode":"0"}
DEBUG:msmart.cloud:Retrying API call: 'user/login'`

**Comment by mac-zhou** [comment]
`password error，please enter again.`
your password is wrong.
you don't  get the correct token and k1,  of course it doesn't work.

run `midea-discover -d`, i want all of output.

**Comment by SebastianStorb** [comment]
```
sebastian@debian-server:~$ midea-discover -a sebastian@XXXXXXXXX -p XXXXXXXXX -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:msmart.scanner:Broadcast message sent: 0
DEBUG:msmart.scanner:Midea Local Data 192.168.1.51 837000b8200f04075a5a0111a8007a800000000000000000000000006938000000150000000000000000000000000000645bc8591e768667ddb4a5ea4106d21a7ea68da00601c5f2f7d7a54947ac851205c86e0c675124c4a3b3666b7c466968724a475e8584b76ad83ef522d6cbf8e9f6e1ffd30d0527659e7e6e507cf066981fca94541303884c52e880ddefc03190f31443d17c3aac03a7656614ae1dca44544d657e733532af39d28bf238602a7cfbf6563ba8bcb1c7b3cd63a4015cd50f
DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.51 3301a8c02c19000030303030303050303030303030305131353032444242343438383846303030300b6e65745f61635f383838460000000001000000040000000000ac00000000000000502dbb44888f069fcd0300080103000000000000000000000000000000000000000000
DEBUG:msmart.scanner:Midea Local Data 192.168.1.41 837000b8200f05a55a5a0111a8007a800000000000000000000000001ddf010000110000000000000000000000000000984d00b2d4c9263d389dcba34c333c0d7c5179b1de29da3850d76d9beb6696c409d094ea8b5ab078c36ae5db0d63e565500a7ef43d08fc8f1f9d1c4e319efd2f3e5cce0f502b5f189b3079db9497184890b13be000894715b606127e07c2fecff31443d17c3aac03a7656614ae1dca4404f3a7497fbe906fdebca8c21eebc5eca7759d2f40f4337298b27ea5c7a4d798
DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.41 2901a8c02c19000030303030303050303030303030305131353032444242353945354334303030300b6e65745f61635f453543340000000001000000040000000000ac00000000000000502dbb59e5c4069fcd0300080103010000000000000000000000000000000000000000
DEBUG:msmart.scanner:Socket timeout
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"1752f479-c130-4b8d-87a9-033f3f69f42c"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"9c5d7b92-42fb-440b-baf4-2e0889bd1fe3"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"password error，please enter again.","errorCode":"3101"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"19c145c9-dbdd-4a0f-bd04-cca91e1bcd90"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"sebastian@storb.net","sessionId":"c9c56d48650248f99229da1990ef82d720210910065100290","accessToken":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","userId":"xxxxxx","versionCode":"","leftCount":""},"errorCode":"0"}
DEBUG:msmart.cloud:Retrying API call: 'user/login'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"8a7b1404-d74c-4fd9-8c82-350570fc317e"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"sebastian@XXXXXXXXX","sessionId":"2103772244304ec8b03cc3dfc6d2c31b20210910065101214","accessToken":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","userId":"xxxxxx","versionCode":"","leftCount":""},"errorCode":"0"}
```

[......]
not ending

**Comment by mac-zhou** [comment]
Does your password have special characters？
If it doesn’t work anymore, just use the default account and password.
You may need to reinstall `msmart`.
```shell
 pip3 uninstall msmart
 pip3 install msmart
```

**Comment by SebastianStorb** [comment]
No Sir, i did not have special characters (because i had changed my password in the app) Now I changed it again to
Test1234.
i had reinstalled msmart before, and did it again it again:
```
sebastian@debian-server:/home$ midea-discover -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:msmart.scanner:Broadcast message sent: 0
DEBUG:msmart.scanner:Midea Local Data 192.168.1.51 837000b8200f04035a5a0111a8007a800000000000000000000000006938000000150000000000000000000000000000645bc8591e768667ddb4a5ea4106d21a7ea68da00601c5f2f7d7a54947ac851205c86e0c675124c4a3b3666b7c466968724a475e8584b76ad83ef522d6cbf8e9f6e1ffd30d0527659e7e6e507cf066981fca94541303884c52e880ddefc03190f31443d17c3aac03a7656614ae1dca44544d657e733532af39d28bf238602a7cfbf6563ba8bcb1c7b3cd63a4015cd50f
DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.51 3301a8c02c19000030303030303050303030303030305131353032444242343438383846303030300b6e65745f61635f383838460000000001000000040000000000ac00000000000000502dbb44888f069fcd0300080103000000000000000000000000000000000000000000
DEBUG:msmart.scanner:Midea Local Data 192.168.1.41 837000b8200f05ac5a5a0111a8007a800000000000000000000000001ddf010000110000000000000000000000000000984d00b2d4c9263d389dcba34c333c0d7c5179b1de29da3850d76d9beb6696c409d094ea8b5ab078c36ae5db0d63e565500a7ef43d08fc8f1f9d1c4e319efd2f3e5cce0f502b5f189b3079db9497184890b13be000894715b606127e07c2fecff31443d17c3aac03a7656614ae1dca4404f3a7497fbe906fdebca8c21eebc5eca7759d2f40f4337298b27ea5c7a4d798
DEBUG:msmart.scanner:Decrypt Reply: 192.168.1.41 2901a8c02c19000030303030303050303030303030305131353032444242353945354334303030300b6e65745f61635f453543340000000001000000040000000000ac00000000000000502dbb59e5c4069fcd0300080103010000000000000000000000000000000000000000
DEBUG:msmart.scanner:Socket timeout
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"c2315776-0a21-4e56-b324-cfd02d80e6d7"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"9b1f0c9b-eea8-4e1a-ba1a-55761e6bd35e"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"password error，please enter again.","errorCode":"3101"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"efcbb2de-a100-4ed5-849b-02ba1109fabd"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"midea_is_best@outlook.com","sessionId":"4bb24d1284dd456db557585b78c6635920210910132616509","accessToken":"54175b43ee49f625d94c63d1ecc53365b920ebb829d567559397ded751813801","userId":"4826094","versionCode":"","leftCount":""},"errorCode":"0"}
DEBUG:msmart.cloud:Retrying API call: 'user/login'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"loginId":"a4f00d0e-62b7-4069-9d75-ce4239b6bab8"},"errorCode":"0"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","result":{"originPrivateVersion":"","nickname":"midea_is_best@outlook.com","sessionId":"3cb73c11f62a4530b35e0d198d47b2d720210910132617574","accessToken":"ddae50080164d86ac571ec2fceac1878b920ebb829d567559397ded751813801","userId":"4826094","versionCode":"","leftCount":""},"errorCode":"0"}
DEBUG:msmart.cloud:Retrying API call: 'user/login'
```

**Comment by SebastianStorb** [comment]
I changed my password again, because it did not help.

What can I do?

**Comment by mac-zhou** [comment]
i just updated，please try:
```shell
pip3 uninstall msmart
pip3 install git+https://github.com/mac-zhou/midea-msmart
```

**Comment by SebastianStorb** [comment]
You solved this bug:
INFO:msmart.cli:*** Found a device: {'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.1.51', 'id': 23XXXXXXXXXXXX, 'port': 6444, 'token': '8AA0A1181BAC26461843B96780BDD1D1375DFD6D3A151199B8FA46CF076078B7EEAAEAAE3181DDBDF7E034A779061FD686DEFB1E90E0DAE6DCDFBF3AAEFCAE28', 'key': '49DBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'ssid': 'net_ac_XXXX'} INFO:msmart.cli:*** Found a device: {'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.1.41', 'id': 18XXXXXXXXXXXX, 'port': 6444, 'token': '4E4416432AB917D4B7604AC9D053F95E85374FEB827D4E137D506A1E7596C6CF576E0FEF16C9069A775F5868B3C6C661FDDC184143DD42916F4F89A5D9D6B895', 'key': '1524XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'ssid': 'net_ac_XXXX'} sebastian@debian-server:~$

but the ACs are still not working:

Do I have to configure something else than configuration.yamal?
Is something wrong in my configuration.yaml?

# Midea_AC
climate:
  - platform: midea_ac
    host: 192.168.1.41
    id: 18XXXXXXXXXXXX
    token: 4E4416432AB917D4B7604AC9D053F95E85374FEB827D4E137D506A1E7596C6CF576E0FEF16C9069A775F5868B3C6C661FDDC184143DD42916F4F89A5D9D6B895
    port: 6444

climate:
  - platform: midea_ac
    host: 192.168.1.51
    id: 23XXXXXXXXXXXX
    token: 
8AA0A1181BAC26461843B96780BDD1D1375DFD6D3A151199B8FA46CF076078B7EEAAEAAE3181DDBDF7E034A779061FD686DEFB1E90E0DAE6DCDFBF3AAEFCAE28
    port: 6444

**Comment by mac-zhou** [comment]
my configuration.yaml is wrong,  k1(key) is missing.
```yaml
climate:
  - platform: midea_ac
    host: 192.168.1.41
    id: 18XXXXXXXXXXXX
    token: <midea-discover output token>
    k1: <midea-discover output key>
  - platform: midea_ac
    host: 192.168.1.51
    id: 23XXXXXXXXXXXX
    token: <midea-discover output token>
    k1: <midea-discover output key>
```

**Comment by SebastianStorb** [comment]
Everything is going great! Thank you very much for your first-class help and the quick turnover! I was really happy about it!

PS: If you want to improve the module: Maybe there is another idea: It would be great to be able to switch the LED (which e.g. shows the temperature) on the inverter of the air conditioning system on and off.

;-))

**Comment by mac-zhou** [comment]
> Everything is going great! Thank you very much for your first-class help and the quick turnover! I was really happy about it!
> 
> PS: If you want to improve the module: Maybe there is another idea: It would be great to be able to switch the LED (which e.g. shows the temperature) on the inverter of the air conditioning system on and off.
> 
> ;-))

new integration are being planned. 
thank you for your donation.
